osrg/gobgp

api/rest.go
added api to show golang statistics.
api response sample:
```
% curl -s "http://127.0.0.1:8080/stats" | jq '.'
{
"time": 1420593644090014500,
"go_version": "go1.3.3",
"go_os": "darwin",
"go_arch": "amd64",
"cpu_num": 4,
"goroutine_num": 11,
"gomaxprocs": 4,
"cgo_call_num": 0,
"memory_alloc": 562056,
"memory_total_alloc": 1222520,
"memory_sys": 5703928,
"memory_lookups": 103,
"memory_mallocs": 3559,
"memory_frees": 2508,
"memory_stack": 360448,
"heap_alloc": 562056,
"heap_sys": 2097152,
"heap_idle": 1097728,
"heap_inuse": 999424,
"heap_released": 0,
"heap_objects": 1051,
"gc_next": 972368,
"gc_last": 1420593638961659600,
"gc_num": 4,
"gc_per_second": 0,
"gc_pause_per_second": 0,
"gc_pause": []
}
```
=> rest: add stats api

api/rest.go, cli/gobgpcli, config/default.go, packet/bgp.go, server/peer.go, server/peer_test.go, server/server.go, table/message.go, table/path.go, table/path_test.go, table/table_manager.go, table/table_manager_test.go
struct Path has a flag which can tell whether the path is withdrawal
path or not. so table.ProcessPaths() needs not to return withdrawal path
and non-withdrawal path separetly.
this removes such unnecessary distinction.
=> table: remove unnecessary distinction of paths

server/peer.go
When route family is not supported for a peer's local rib,
gobgpd dies with following message.
$ gobgp show neighbor 10.0.0.1 local evpn
> panic: interface conversion: interface is nil, not *api.Destination
this patch fix this.
=> server: bug fix of REQ_LOCAL_RIB handling

gobgp/main.go
=> gobgp: fix showing neighbor info twice

api/gobgp.pb.go
=> api: regenerate gobgp.pb.go to adapt the latest grpc implementation

server/fsm.go
If a negotiated hold time is smaller than a configured hold time, we use
one third of the negotiated hold time for a keepalive interval.
=> server: keepalive interval should be honor a negotiated hold time

api/gobgp.pb.go, api/gobgp.proto, gobgp/main.go, server/peer.go
fujita@ubuntu:~/git/gobgp/gobgp$ go run main.go neighbor 10.0.255.1
BGP neighbor is 10.0.255.1, remote AS 65001
BGP version 4, remote router ID 192.168.0.1
BGP state = BGP_FSM_ESTABLISHED, up for 00:11:55
BGP OutQ = 0, Flops = 0
Hold time is 30, keepalive interval is 10 seconds
Configured hold time is 90, keepalive interval is 30 seconds
Neighbor capabilities:
MULTIPROTOCOL: advertised and received
ROUTE_REFRESH: advertised and received
FOUR_OCTET_AS_NUMBER: advertised and received
ROUTE_REFRESH_CISCO: received
Message statistics:
Sent       Rcvd
Opens:                  1          1
Notifications:          0          0
Updates:                1          1
Keepalives:            72         73
Route Refesh:           0          0
Discarded:              0          0
Total: …
=> cli: show configured and negotiated holdtime and keepalive interval

gobgp/main.go
Use transport address (ipv4 or v6) as a hint.
=> cli: set wisely address family if not specified

server/peer.go, server/server.go
fix the above issue with route server use case.
=> server: don't path information to the same AS number peer

api/gobgp.pb.go, api/gobgp.proto, gobgp/neighbor.go, packet/bgp.go
changed AS_PATH string format based on AS_PATH segment type as follows.
- AS_SEQ
```
Network          Next Hop   AS_PATH          Age        Attrs
*> 192.168.100.0/24 10.0.0.100 1 2 3            00:00:00   [{Origin: IGP}]
```
- AS_SET
```
Network          Next Hop   AS_PATH       Age        Attrs
*> 192.168.100.0/24 10.0.0.100 1 2 3 {4,5,6} 00:00:05   [{Origin: IGP}]
```
- AS_CONFED_SEQ
```
Network        Next Hop   AS_PATH       Age        Attrs
*> 192.168.100.0/24 10.0.0.100 1 2 3 (4 5 6) 00:06:55   [{Origin: IGP}]
```
- AS_CONFED_SET
```
Network        Next Hop   AS_PATH      Age        Attrs
*> 192.168.100.0/24 10.0.0.100 1 2 3 [4,5,6] 00:00:01   [{Origin: IGP}]
```
=> cli: fix AS_PATH string format

packet/bgp.go, packet/bgp_test.go, policy/policy_test.go, table/destination.go, table/destination_test.go, table/path.go, table/path_test.go
ASLen() in AsPathParam and As4PathParam returns the number of AS number based on the segment type.
segment type                   | length to be returned (based on RFC5065)
--------------------------------- | -------------
AS_SET                           | 1 
AS_SEQ                          | actual AS length 
AS_CONFED_SEQ         | 0
AS_CONFED_SET         | 0
=> Aspath count

packet/bgp.go
RouteDistinguisherIPAddressAS.Value.Admin is a net.IP, which is 16-byte long, while administrator sub field of an RD is 4 byte-long
=> packet: fix IPAddressAS RD serialization

test/scenario_test/docker_control.py, test/scenario_test/route_server_policy_test.py
fixed problem that policy scenario test fails if gobgp container doesn't exists at the beginning of the test,
and also readjusted the retry's order and waiting time for stoping docker container.
=> scenario_test: check gobgp container before remove in its preparation

docs/sources/cli-command-syntax.md, gobgp/global.go, gobgp/neighbor.go
$ gobgp global rib
Network     Next Hop AS_PATH Age        Attrs
*> 10.0.0.0/24 0.0.0.0  65000   00:10:17   [{Origin: IGP}]
*> 10.0.0.0/25 0.0.0.0  65000   00:10:16   [{Origin: IGP}]
*> 10.0.0.0/26 0.0.0.0  65000   00:10:15   [{Origin: IGP}]
*> 10.0.1.0/24 0.0.0.0  65000   00:10:21   [{Origin: IGP}]
*> 10.0.2.0/24 0.0.0.0  65000   00:10:20   [{Origin: IGP}]
$ gobgp global rib 10.0.0.0/24
Network     Next Hop AS_PATH Age        Attrs
*> 10.0.0.0/24 0.0.0.0  65000   00:10:54   [{Origin: IGP}]
$ gobgp global rib 10.0.0.10
Network     Next Hop AS_PATH Age        Attrs
*> 10.0.0.0/26 0.0.0.0  65000   00:11:16   [{Origin: IGP}]
=> cli: add support of route filtering in show commands

server/server.go, table/path.go, test/scenario_test/bgp_router_test.py, test/scenario_test/lib/base.py, test/scenario_test/lib/gobgp.py
When gobgp originates a route, the generated route had incorrect
as-path. this patch fix this bug.
Scenario test is also added to check this.
[before]
$ gobgp neighbor global rib
Network      Next Hop     AS_PATH     Age        Attrs
*> 10.0.1.0/24  192.168.10.3 65001       00:03:20   [{Origin: IGP} {Med: 0}]
*> 10.0.2.0/24  192.168.10.4 65002       00:03:36   [{Origin: IGP} {Med: 200}]
*> 10.10.0.0/24 0.0.0.0      65000       00:03:37   [{Origin: IGP}]
$ gobgp neighbor 192.168.10.5 adj-out
Network      Next Hop     AS_PATH     Attrs
10.0.1.0/24  192.168.10.2 65000 65001 [{Origin: IGP}]
10.0.2.0/24  192.168.10.2 65000 65002 [{Origin: IGP}]
10.10.0.0/24 192.168.10.2 65000 65000 [{Origin: IGP}]
[after]
$ gobgp neighbor global rib
Network      Next Hop     AS_PATH     Age        Attrs
*> …
=> server: bug fix of extra as-path prepending

server/grpc_server.go
aimed at preventing drop of monitoring notification
=> server: enable buffering for grpc response

server/server.go
Currently, if a mrt request sender doesn't read from bgpd some time, a
message could be dropped. Instead, this makes bgpd keep messages in
memory until they are read.
=> server: make mrt rpc request reliable

test/scenario_test/ci-scripts/jenkins-build-script.sh
Tested-by: Hiroshi Yokoi <yokoi.hirochi@po.ntts.co.jp>
=> test: fix missing sudo to remove useless docker images correctly

api/gobgp.pb.go, api/gobgp.proto, gobgp/common.go, gobgp/main.go, gobgp/rpki.go, gobgpd/main.go, server/grpc_server.go, server/rpki.go, server/server.go
Just get info from ROA server. Not varidate any route yet.
Currently, "--rpki-server" option enables RPKI:
$ gobgpd --rpki-server 210.173.170.254:323
We'll use the configuration file for this later.
You can see ROAs via CLI:
$ gobgp rpki
For ipv6,
$ gobgp rpki -a v6
=> add RPKI support

server/peer.go
TODO: we calculate the number every time a CLI request comes. we
should store the number somewhere.
=> server: fix 'accepted' number in peer

server/fsm.go
The config file should be like:
[Neighbors]
[[Neighbors.NeighborList]]
[Neighbors.NeighborList.NeighborConfig]
PeerAs = 65001
NeighborAddress = "10.0.255.1"
[Neighbors.NeighborList.NeighborState]
AdminDown = true
=> server: support adminDown'ed peer startup

policy/policy.go
You can configure like (NotFound:1, Valid:2, Invalid:3):
[PolicyDefinitions]
[[PolicyDefinitions.PolicyDefinitionList]]
Name = "AS65002-EXPORT-RPKI"
[PolicyDefinitions.PolicyDefinitionList.Statements]
[[PolicyDefinitions.PolicyDefinitionList.Statements.StatementList]]
Name = "statement1"
[PolicyDefinitions.PolicyDefinitionList.Statements.StatementList.Conditions]
[PolicyDefinitions.PolicyDefinitionList.Statements.StatementList.Conditions.BgpConditions]
RpkiValidationResult = 3
[PolicyDefinitions.PolicyDefinitionList.Statements.StatementList.Actions]
[PolicyDefinitions.PolicyDefinitionList.Statements.StatementList.Actions.RouteDisposition]
RejectRoute = true
=> policy: support rpki validation match

packet/bgp.go, table/message.go
With this patch, bobgpd packs multiple NLRIs into one BGP update
message (IOW, multiple paths into one update message).
We do only with ipv4 since we could have lots of routes. If you don't
have lots, it's not worth having the complicated logic for such route
families.
=> pack multiple NLRIs into one BGP update message

packet/mrt.go, packet/mrt_test.go
Commiting helper function on MRTHeader to return a golang time.Time
from the timestamp. Also commiting the relevant test function.
=> mrt: add helper function for timestamp

packet/bgp.go
The draft was promoted to IETF WG item.
It is already enqueued to RFC editors in Aug. 2015. It's expected to be published as RFC soon.
Signed-off-by: Jun-ya Kato <kato.junya@lab.ntt.co.jp>
=> packet: update reference to 'draft-haas-idr-flowspec-redirect-rt-bis'

server/fsm.go, server/peer.go
You can enable the feature like the following:
[Neighbors]
[[Neighbors.NeighborList]]
[Neighbors.NeighborList.NeighborConfig]
PeerAs = 65001
NeighborAddress = "10.0.255.1"
[Neighbors.NeighborList.EbgpMultihop]
[Neighbors.NeighborList.EbgpMultihop.EbgpMultihopConfig]
Enabled = true
MultihopTtl = 8
=> support multihop ttl

server/rpki.go, server/server.go
gobgp asks for non existing thing (e.g. local rib for non route server
peer), gobgpd doesn't send anything so gobgp will hang up.
This fixes gobgpd to send an empty response.
=> server: fix gobgp hang

server/fsm.go
if you don't specify ttl, then we use the OS-default ttl.
=> improve multihop ttl support

gobgpd/main.go
--cpus option can be used to specify to the number of CPUs to be
used. IOW, the specified number is passed to runtime.GOMAXPROCS().
=> gobgpd: add command line option to specify #CPUs to be used

config/bgp_configs.go, server/dumper.go, server/server.go, tools/pyang_plugins/gobgp.yang
You can enable the feature like:
[Global]
[Global.GlobalConfig]
As = 64512
RouterId = "10.0.255.254"
[Global.Mrt]
FileName = "update.dump"
=> server: add mrt bgp4mp support

packet/bgp.go, test/scenario_test/ci-scripts/jenkins-build-script.sh
handle failure of regexp matching
also add support of the syntax below
// added syntax
$ gobgp rib add -a ipv4-flowspec match port 8080 then discard
// original syntax (still supported)
$ gobgp rib add -a ipv4-flowspec match port '=8080' then discard
=> packet: bug fix of flowspec numeric parser

config/bgp_configs.go, gobgpd/main.go, packet/bmp.go, server/bmp.go, server/fsm.go, server/peer.go, server/server.go, tools/pyang_plugins/gobgp.yang
Can be enabled like:
[Global]
[Global.GlobalConfig]
As = 64512
RouterId = "10.0.255.254"
[BmpServers]
[[BmpServers.BmpServerList]]
[BmpServers.BmpServerList.BmpServerConfig]
Address = "127.0.0.1"
Port=11019
=> Add bmp support

gobmpd/main.go
Currently, just accepts a conneciton and print received messages in
the json format.
=> add bmpd server

test/scenario_test/ci-scripts/jenkins-build-script.sh
This patch copies docker.log and nosetest logs of the test which is invoked by Jenkins to object storage.
In addition, it clears docker.log before removing previous docker containers.
=> scenario_test: preserve test logs

test/scenario_test/lib/base.py
does not use a 'docker rm -f' command when stop the quagga
=> fix way for stop the quagga

api/gobgp.pb.go, api/gobgp.proto, gobgp/cmd/common.go, gobgp/cmd/global.go, gobgp/cmd/monitor.go, gobgp/cmd/mrt.go, gobgp/cmd/neighbor.go, gobgp/cmd/policy.go, gobgp/cmd/root.go, gobgp/cmd/rpki.go, gobgp/cmd/vrf.go, policy/policy.go, server/grpc_server.go, server/peer.go, server/rpki.go, server/server.go, table/destination.go, table/path.go, table/vrf.go
api/Grpc is too general for package/service name.
rename them to gobgpapi/GobgpApi.
=> api: rename package/service name to gobgpapi

config/bgp_configs.go, docs/sources/zebra.md, server/server.go, server/zclient.go, test/scenario_test/lib/gobgp.py, test/scenario_test/lib/quagga.py, tools/pyang_plugins/bgpyang2golang.py, tools/pyang_plugins/gobgp.yang, zebra/zapi.go
Current implementation was to redistribute all route types include connected routes.
In typical deployment, we only want to redistribute IGP routes.
This PR enables to specify which route type you want to redistribute through gobgp.
=> enable to redistribute specific route type

policy/policy.go
Contains() is very slow so let's avoid it if possible.
=> policy: improve ipPrefixCalculate performance slightly

gobgp/cmd/neighbor.go
=> gobgp: restore --transport option for neighbor command

server/server.go, table/table_manager.go
soft reset out needs to use routes in the local table instead of the
adj-in. The export policy will be applied correctly.
=> server: fix soft reset out

gobgp/cmd/common.go
ipv4 should be used if an address family is not specified.
=> gobpg: fix global command

packet/bgp.go
Will fix lint error of  these:
```
$ go vet packet/*.go
packet/bgp.go:333: struct field tag `json"tuples"` not compatible with reflect.StructTag.Get
packet/bgp.go:408: struct field tag `json"code"` not compatible with reflect.StructTag.Get
packet/bgp.go:409: struct field tag `json"value"` not compatible with reflect.StructTag.Get
packet/bgp.go:475: struct field tag `json"code"` not compatible with reflect.StructTag.Get
```
=> packet: fix incompatible struct field tags

gobgp/cmd/global.go, packet/bgp.go, packet/bmp.go
I fixed warnings detected by  ```go vet``` in global.go, bgp.go and bmp.go.
=> Go vet fix

server/server.go
We can't update #accepted with a specific rf.
=> server: remove wrong updateAccepted call

table/path.go, table/path_test.go, table/policy.go
1. use radix-tree for prefix matching
2. stop using regexp for simple as-path-set matching
=> speed up policy matching

api/gobgp.pb.go, api/gobgp.proto, gobgp/cmd/global.go, gobgpd/main.go, server/grpc_server.go, server/server.go
add grpc api to configure global as/router-id
$ gobgp global as 65000 router-id 10.0.0.1
=> server: enable to start without configuration file

api/gobgp.pb.go, api/gobgp.proto, gobgp/cmd/common.go, server/peer.go, server/server.go
bug fix: get neighbor cmd get neighbor address as remote router id.
Signed-off-by: YujiOshima <yuji.oshima0x3fd@gmail.com>
=> cmd/api: get peer remote router id not neighbor address

docs/sources/cli-command-syntax.md
Network prefix is required rather than just IP.
=> doc: correct the example of rib add command

packet/bgp.go
Properly serializes LinkLocalNexthop.
=> packet: fix PathAttributeMpReachNLRI's Serialize()

packet/bmp.go, packet/mrt.go, server/bmp.go, server/fsm.go, server/server.go, server/watcher.go
bgpd parse on-wire original update data to construct BGPMessage object
and serialize it. Sometimes the both data is not idential. For
example, the original data sets the extended length for attribute even
if the length is less than 256.
This commit fixes the above issue.
=> mrt: use on-wire original update data for mrt

packet/bgp.go
net.IP handles IPv4-mapped addresss as ipv4 so leads to the following
crash:
gobgpd[857]: /usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
gobgpd[857]: github.com/osrg/gobgp/table.CidrToRadixkey(0xc2080ffec0, 0xa, 0x0, 0x0)
gobgpd[857]: /usr/local/opt/go/src/github.com/osrg/gobgp/table/destination.go:63 +0xb2
=> fix IPv4-mapped addresss handling

packet/bmp.go, packet/bmp_test.go
=> bmp: fix ParseBMPMessage to handle failure of parsing header

api/gobgp.pb.go, api/gobgp.proto, docs/sources/cli-command-syntax.md, gobgp/cmd/neighbor.go, server/server.go
$ gobgp global rib
Network      Next Hop  AS_PATH  Age       Attrs
*>  10.0.0.0/24  0.0.0.0            00:00:01  [{Origin: ?}]
$ gobgp global rib 10.0.0.0/20
Network not in table
$ gobgp global rib 10.0.0.0/20 longer-prefix
Network      Next Hop  AS_PATH  Age       Attrs
*>  10.0.0.0/24  0.0.0.0            00:00:01  [{Origin: ?}]
=> api/cli: support showing longer-prefix

server/server.go
We don't import as loop path into rs peer's table. So no need to check
again.
=> server: avoid as loop check in filterpath() for rs peer

gobgp/cmd/rpki.go
zero uptime means gobgpd never connected to roa server.
=> gobgp: fix rpki cli uptime

config/bgp_configs.go, server/bmp.go, server/server.go, server/zclient.go, tools/pyang_plugins/gobgp.yang
"RouteMonitoringPolicy" option added:
0: pre-policy (by default)
1: post-policy
2: both
=
[BmpServers]
[[BmpServers.BmpServerList]]
[BmpServers.BmpServerList.BmpServerConfig]
Address = "127.0.0.1"
Port = 11019
RouteMonitoringPolicy = 2
=> bmp: support post-policy routing monitoring

table/message.go, table/message_test.go
post-policy code creates paths from bgp update and then create the
message from the modified paths. MP_UNREACH needs to be handled
diffently.
=> bmp: fix post-policy bmp message creation

server/fsm.go, server/fsm_test.go, server/peer.go, server/server.go, test/lib/gobgp.py, test/performance_test/main.go
These patches tries to make GoBGP robust under heavy load. (e.g. 1000 peers, each of them advertises  100 routes)
`fsmincomingch` was used to pass **both** BGP state change info and BGP update msg.
When many BGP update msgs occupy `fsmincomingch`, it takes long time for BGP state change
info to be handled. In worst case, hold-timer of peers triggered and session disconnects.
To solve this problem, https://github.com/osrg/gobgp/commit/afcd2e72fbe12e9ad8ab426e14c7110123678bad introduces fastpath for BGP state change. BGP state change will be handled early in the main loop and FSM handling will be much more robust.
Another problem around `fsmincomingch` is when it's buffer is fully occupied, `(*FSMHandler).recvMessageloop()` blocks. This means that a keepalive msg from peers can't be …
=> make GoBGP robust under heavy load

gobgp/cmd/neighbor.go
fix the regression due the following commit:
commit b0fbcc6b1b18d2c9fe67437fe6432914b67c5508
Author: ISHIDA Wataru <ishida.wataru@lab.ntt.co.jp>
Date:   Fri Jan 8 11:52:07 2016 +0900
config: change enum value type to string for ease of configuration
=> rpki: fix showing rpki results

server/fsm.go
give random.Intn() MIN_CONNECT_RETRY(10s) instead of connect-retry
(120s by default).
=> server: make initial active connect faster

packet/bmp.go
=> packet: bmp localaddress in peerup message

server/server.go
fix the regression due to c9436bc
=> server: fix socket md5

table/path.go
eor path needs a filter map. Otherwise gobgpd crashes.
=> table: fix gracefull restart regression

table/policy.go
Since communities/ext-communities are tested one by one in policy-condition,
we don't need '^' and '$' around match condition items.
=> policy: remove unnecessary regexp special charactor

.gitignore
=> .gitignore: remove old gomrt/gomrt binary

table/path.go, table/path_test.go
rfc4271 says the sender of an UPDATE message SHOULD order path attributes.
=> sort path attributes

server/server.go
AS in an OpenMsg is set to zero if a peer is configured via grpc.
commit 0b78f57ccdf63591fd211ade0b571189e070f598
Author: ISHIDA Wataru <ishida.wataru@lab.ntt.co.jp>
Date:   Fri Feb 19 15:40:30 2016 +0900
config/server: support per-peer asn
=> server: fix per-asn regression

packet/bgp.go
If FlowSpecComponentItem object is created by API (e.g. CLI), the
length info in its Op isn't initialized. So its Len() returns a bogus
value. This patch initializes the length info when creating the object
instead of its Serialize().
https://github.com/osrg/gobgp/issues/753
=> packet: fix FlowSpecComponentItem Len()

server/fsm.go
when hold timer expires, established() goroutine exits so even if tx()
goroutine writes to errorCh, nobody closes the connection. The, rx()
goroutine doesn't finish, so gobgpd hits panic().
This reverts commit 38bd31856b5eff046a4874e83b53cb7d3e45cdaf.
Conflicts:
server/fsm.go
=> Revert "fsm: remove redundant connection close"

gobgpd/main.go
Sending signal USR1 to run GC and return free memory to OS. It's for
debugging memory leak.
Maybe we could support this feature via the GRPC API.
=> gobgpd: support force GC and return free memory to OS

table/table.go
In the current implementation, the destinations map management area in the table has not been initialized even if destinations removed all.
Therefore, to explicitly initialize the destinations.
=> table: initialize the destinations when the destinations is empty

packet/bgp/bgp.go
Fixes a possible crash in  BGPOpen's DecodeFromBytes().
fixes #818
=> packet: handle malformed option param length in OpenMessage

gobgp/main.go, server/grpc_server.go
By default, grpc traces rpc events. GoBGP sends a load of data
(e.g. showing global rib, injecting via mrt, etc). As a result, GoBGP
consumes huge memory if you send/receive data via RPC. Let's disable
tracing.
=> grpc: disable tracing to avoid consuming massive memory

gobgpd/main.go, server/grpc_server.go
by default, ":50051" is used as before.
gobgpd accepts grpc connections from localhost with the following
example:
$ gobgpd --api-hosts 127.0.0.1:50051
You can specify multiple hosts like:
$ gobgpd --api-hosts 127.0.0.1:50051,10.0.255.254:50051
close #796
=> specify api hosts that gobgpd listens on

config/bgp_configs.go, server/fsm.go, tools/pyang_plugins/gobgp.yang
Allow user to setup neighbor BGP TCP port (Default is 179)
=> Add neighbor-port-number to bgp neighbor config

.travis.yml
travis-ci can't set up go1.3 env for now. Let's accept the failure on
go1.3 and see if this failure is permanent or not.
=> test: allow travis-ci failure on go1.3

gobgp/cmd/policy.go
use DEL_ALL to delete statement
=> cli: fix wrong modStatement operation

config/bgp_configs.go, config/default.go, config/util.go, docs/sources/configuration.md, docs/sources/evpn.md, docs/sources/flowspec.md, docs/sources/graceful-restart.md, server/fsm.go, server/peer.go, server/server.go, test/lib/gobgp.py, tools/config/example_toml.go, tools/pyang_plugins/bgpyang2golang.py
stop generating self-contained leafref fields in openconfig model.
(e.g. bgp:neighbor/bgp:neighbor-address )
=> config: simplify config structures

config/serve.go, gobgpd/main.go
avoid reconfiguration when policy configuration is not changed
=> config: fix bug of UpdateConfig()

.travis.yml
travis-ci can't set up go1.4 env for now. Let's accept the failure on
go1.4 and see if this failure is permanent or not.
=> test: allow travis-ci failure on go1.4

openswitch/openswitch.go
The version of libovsdb that osrg forked uses
github.com/socketplane/libovsdb/Godeps/, which has gone now. So our
fork doesn't work any more.
Let's try to use socketplane/libovsdb.
=> use socketplane/libovsdb instead of osrg fork

server/fsm.go, server/server.go
Changing some of configuration leads to sending a notification. So the
reason of the BGP state change should be the notification.
The main goroutine sends a notification, closes the connection, kill
goroutines for the peer. So With the current code, the reason could be
"rx failure", "tx failure", or "dying". To avoid that, this patch adds
kinda workaround.
=> server: print correct reason of state change by configuration change

gobgp/cmd/neighbor.go
current interval(state) and that of configured(config) can be different
=> cli: fix to show current keepalive interval

server/zclient.go
sending REDISTRIBUTE_DEFAULT_ADD command causes getting every routes
zebra has which is not desirable behavior
=> server: fix wrong usage of zapi

table/destination.go
The current code uses Path.Equal(), which just check out if pathes are
idential. However, it doesn't work for two cloned pathes of a path
(soft update in case).
=> table: fix to compare new best path with old best path

server/server.go, test/lib/gobgp.py
regression introduced by 4c9cd88c61cb848e36a45657b7cbc63b9c783dc4
also fix test/lib to test configuration without local-address
(configure local-address only if neighbor-address is IPv6)
=> server: fix active connection regression

server/server.go, test/scenario_test/bgp_router_test.py
Another regression introduced by 4c9cd88c61cb848e36a45657b7cbc63b9c783dc4
Previous fix (81bc3851b2c1f112f157b98a3cf60757a199a31a) fixes active
connection of neighbors configured via configuration file.
This fixes that of neighbors configured via gRPC API.
Test is also added.
=> server: fix another regression of active connection

table/destination.go, table/destination_test.go, test/scenario_test/route_server_test.py
Needs the first AS in the AS_SEQUENCE is the same for multiple
paths. Any preceding AS_CONFED_SEQUENCE is ignored.
Also rename the function name to 'firstAS'.
=> table: fix leftmostAS() in compareByMED

server/fsm.go
We can't use the two-bytes AS translation result by the previous
session. IOW, the peer might become 4bytes AS capable after the
session was down.
fix the regression of
commit 6f644ee1ca1be81e6ec96c8504e34c26b3d1f8a8
Author: FUJITA Tomonori <fujita.tomonori@lab.ntt.co.jp>
Date:   Tue Jun 28 10:44:07 2016 +0900
fsm: do two-bytes AS translation if didn't sent 4byte cap
=> fix two-bytes AS translation

gobgpd/main.go, server/server.go
The useage of policyMutex is very hacky. It should be moved to table/policy.go
=> server: add missing mutex lock when updating policy configuration

gobgp/cmd/common.go, gobgp/cmd/mrt.go, table/destination.go, table/destination_test.go, table/table.go
$ gobgp mrt inject global --only-best your-mrt-dump-file
=> gobgp: support mrt injecting only best paths

server/server.go
policy.Reset() won't initialize global policy unless we pass a map
with key table.GLOBAL_RIB_NAME
=> server: add missing default policy setting in (*BgpServer).Start()

api/grpc_server.go, config/bgp_configs.go, config/default.go, server/mrt.go, server/peer.go, tools/pyang_plugins/gobgp.yang
Stop using config.NeighborState's Description in a hacky way for the
remote Router Id.
=> add RemoteRouterId to config.NeighborState

server/sockopt_bsd.go, server/sockopt_linux.go
On some architecture, setsockopt() is a multiplexed syscall and is not
available directly (for example, on i386). Instead of invoking the
syscall directly, use syscall.SetsockoptString() which is safe as strings
are not null-terminated with Go.
On BSD, use syscall.SetsockoptInt(), but I don't know if there are
architectures with the same limitations as for Linux.
Signed-off-by: Vincent Bernat <vincent@bernat.im>
=> server: portability fix for setsockopt() on Linux

table/message.go
RFC4760 says:
An UPDATE message that contains the MP_UNREACH_NLRI is not required to
carry any other path attributes.
=> table: MP_UNREACH_NLRI shouldn't carry any other path attributes

packet/bgp/bgp.go, packet/bgp/bgp_test.go, table/destination_test.go
=> packet/bgp: fix handling of IPv4 mapped IPv6 prefixes

api/grpc_server.go
Hello, I'm Chris. The README.md at this projects root advertises a relaxed contribution policy but allow me to apologize in advance if I missed any process that should have proceeded this pull request.
Motivated by the need for [authentication](http://www.grpc.io/docs/guides/auth.html) on the `grpc.Server` object this change will allow a user to provide their own [grpc.Server](https://godoc.org/google.golang.org/grpc#NewServer) and apply any options like [grpc.Creds](https://godoc.org/google.golang.org/grpc#Creds) for example.
I couldn't find a way to do this without modifying the API since the `api.Server` structs `grpcServer` field is private. I considered adding a getter for the `grpcServer` field but figured that pre-initialization would best align with the original authors intent. I …
=> Allow creating a server with a user specified grpc server.

test/scenario_test/bgp_router_test.py
Since g3's route (MED 10) is weaker than g2's,
g3's route should not be advertised to g2 from g1.
But when g3's route arrives on g1 before g2's, g1 advertises g3's route.
This commit ensures g3's route come after g2's route
=> test: fix bug of bgp_router_test.py

server/fsm.go
creating new `err` variable prevents proper error propagation which
leads to wrongly contine reading BGP messages even after receiving
an invalid update message.
=> server: fix error propagation

test/lib/base.py, test/scenario_test/bgp_router_test.py, test/scenario_test/ibgp_router_test.py
gobgp has two ibgp peers and one ebgp.
1. the best path is from ebgp so advertise it to ibgp peers.
2. one of ibgp peer sends the same path so now the path from ibgp
becomes best.
3. gobgp doesn't advertise it to another ibgp and needs to withdraw
the best from ebgp.
=> test: add change of best paths from ibgp and ebgp

server/server.go, server/util.go
infinite channel has internal goroutine which won't stopp until all items in
the buffer are dequeued.
=> server: fix memory leak in infinite channel goroutine

packet/bgp/bgp.go
When Open Message optional parameter == 1, there is no packet length check for load paramtype and paramlen.  The patch fix the crash issues.
=> Fix Open Message optional parameter length == 1 GoBGP crashes issues.

server/server.go, test/scenario_test/bgp_router_test.py
cleaning outgoing channel while fsm handler is running may cause crash
Dec  2 06:14:36 g2 gobgpd[6955]: {"Topic":"Peer","level":"info","msg":"Delete a peer configuration for:10.173.176.211","time":"2016-12-02T06:14:36Z"}
Dec  2 06:14:36 g2 gobgpd[6955]: {"Data":"","Key":"10.173.176.211","Topic":"Peer","level":"warning","msg":"sent notification","time":"2016-12-02T06:14:36Z"}
Dec  2 06:14:36 g2 gobgpd[6955]: {"Key":"10.173.176.211","Reason":"notification-sent code 6(cease) subcode 3(peer deconfigured)","State":"BGP_FSM_ESTABLISHED","Topic":"Peer","level":"info","msg":"Peer Down","time":"2016-12-02T06:14:36Z"}
Dec  2 06:14:36 g2 gobgpd[6955]: panic: interface conversion: interface {} is nil, not *server.FsmOutgoingMsg
Dec  2 06:14:36 g2 gobgpd[6955]: goroutine 69 [running]:
Dec  2 06:14:36 …
=> server: fix bug of deleteNeighbor()

api/grpc_server.go, table/policy.go
Currently we get error when we use "invert" in statement condition like below.
```
% gobgp global as 65000 router-id 10.10.0.1
% gobgp policy neighbor add n1 172.16.132.11
% gobgp policy statement add statement1
% gobgp policy statement statement1 add condition neighbor n1 invert
rpc error: code = 2 desc = invalid match type
```
This patch fixes the issue.
Signed-off-by: Hiroshi Yokoi <yokoi.hiroshi@po.ntts.co.jp>
=> policy: allow using invert condition in statement

client/client_test.go
before creating new client, we need to ensure GrpcServer is up.
=> client: fix client_test

config/serve.go, config/util.go, config/util_test.go
This patch enables to automatically detect the type of config file
by retrieving the extension from the config file name.
e.g.) "gobgpd.toml" will be assumed as TOML formatted file.
Note: This feature will override the format specified with the cli
"--config-type" option.
=> config: Detect config file type automatically

server/server.go
when using named return for management operations, we need to substitute
the return value of (*BgpServer).mgmtOperation() to a valiable 'err' for
proper error propagation.
close #1215
=> server: fix a bug of error handling

packet/bgp/bgp.go, server/server.go
- All of EoR except IPv4 unicast have MP_UNREACH only. (RFC4724)
- length of the MP_UNREACH attr. should be 3bytes.
- length of the value should be 0bytes.
- Should send EoR marker in initial exchange of BMP Route Monitoring. (RFC7854)
=> Fix End of RIB handling

server/zclient.go, server/zclient_test.go, zebra/zapi.go, zebra/zapi_test.go
Since Quagga 1.0.20160309, it implements per-route MTU handling which
adds MTU attribute to every ZEBRA_IPV4_ROUTE_ADD and
ZEBRA_IPV6_ROUTE_ADD messages. It causes "message length invalid" error
when GoBGP receives messages from Zebra and as the result, routes from
Zebra are no longer added to GoBGP.
This fixes the issue by decoding/encoding MTU attribute properly.
Now parsed MTU attribute is not used anywhere, just kept in an internal
structure.
=> zebra: Process per-route MTU zebra message

table/policy.go
len(cur)-len(ps) is negative if the caller tries to remove more than
currently assigned policies.
=> table: fix DeletePolicyAssignment() crash with bogus input

docs/sources/flowspec.md, gobgp/cmd/global.go, packet/bgp/bgp.go, packet/bgp/constant.go, test/scenario_test/flow_spec_test.py
This patch proposes a new way to configure BGP flowspec TCP flags
rules It allows to comply with RFC 5575 by defining flags like this
=SA =A / '!SA' / '=SA&=!U' = means match, ! means not, & means and,
all TCP flags are identified by their first charater S for SYN A for
Ack ...
=> flowspec: comply with RFC 5575 about TCP flags rules

gobgp/cmd/neighbor.go
before:
$ gobgp n 10.0.0.1 adj-in foo
Network not in table
after:
$ gobgp n 10.0.0.1 adj-in foo
invalid CIDR/IP
=> cli: return error with invalid input

server/server.go, server/server_test.go
with two ibgp peers (a and b), when peer a advertizes one route and
then withdraw it, there are two bugs:
- gobgp sends withdrawal to peer a.
- gobgp sends withdrawal to peer b.
this fixes both.
=> server: fix withdraw with ibgp

test/scenario_test/bgp_router_test.py, test/scenario_test/bgp_zebra_test.py, test/scenario_test/evpn_test.py, test/scenario_test/flow_spec_test.py, test/scenario_test/global_policy_test.py, test/scenario_test/graceful_restart_test.py, test/scenario_test/ibgp_router_test.py, test/scenario_test/long_lived_graceful_restart_test.py, test/scenario_test/route_reflector_test.py, test/scenario_test/route_server_as2_test.py, test/scenario_test/route_server_ipv4_v6_test.py, test/scenario_test/route_server_malformed_test.py, test/scenario_test/route_server_policy_grpc_test.py, test/scenario_test/route_server_policy_test.py, test/scenario_test/route_server_softreset_test.py, test/scenario_test/route_server_test.py, test/scenario_test/route_server_test2.py, test/scenario_test/rtc_test.py, test/scenario_test/run_all_tests.sh, test/scenario_test/vrf_neighbor_test.py, test/scenario_test/vrf_neighbor_test2.py, test/scenario_test/zapi_v3_test.py
To separate Python development environment from OS's Python environment, we can use Python virtualenv.
But to enable the root privilege on virtualenv, we need to specify Python interpreter on its virtualenv.
e.g.)
$ sudo -E .venv/bin/python <script>
Currently, scenario_test requires the root privilege (for Docker execution?), so it is required some modification to scenario_test on virtualenv.
We need to modify all Python interpreter into virtualenv's interpreter in "scenario_test/run_all_tests.sh" for example. 
To solve this problem, this patch removes "sudo" command when running tests.
Note: To enable to execute Docker without the root privilege, please add your local user into "docker" group. With this setting, Docker does not require the root privilege.
Signed-off-by: IWASE Yusuke …
=> scenario_test: Remove "sudo" command prefix for running tests

api/grpc_server.go, table/policy.go
Currently, Prefix structure wrongly handles IPv4-Mapped IPv6 Address
as v4.
=> table: handle IPv4-Mapped IPv6 Address as v6

table/table.go
$ gobgp g r 168.181.21.128/25 shorter-prefixes
Network not in table
$ gobgp g r 168.181.21.0/25 shorter-prefixes
Network             Next Hop             AS_PATH              Age       Attrs
*> 168.181.21.0/24     187.16.221.202       61580                04:17:41  [{Origin: i}]
=> server: fix table query with shorter-prefixes option

packet/bgp/bgp.go
support for IPv6 NLRI with IPv4 nexthop
=> don't To4() nexthop address when AFI is not IPv4

config/default.go, server/peer.go, server/server.go, server/server_test.go
This patch fixes a bug of export policy and implicit withdrawal.
When a path is filtered by export policy, we need to check whether the
old path (implicit withdrawn path) was sent before the new path.
If it has been sent, we need to send a withdrawal message.
=> policy: send a withdrawal if export policy blocks an existing route

server/server.go
when the old best was from iBGP, we don't need to send withdrawals
to iBGP peers.
=> server: avoid sending unwanted withdrawals to iBGP peers

config/bgp_configs.go, config/default.go, docs/sources/bmp.md, docs/sources/configuration.md, packet/bmp/bmp.go, packet/bmp/bmp_test.go, server/bmp.go, server/peer.go, tools/pyang_plugins/gobgp.yang
This PR enables to send BMP statistics reports for the number of routes in Adj-RIBs-In and Loc-RIB.
Also includes the improvements of BMP statistics reports serializer and the updates of documents for BMP configurations.
=> bmp: Stats reports for Adj-RIBs-In and Loc-RIB routes

table/destination.go
=> table: avoid unnecessary memory allocation about generating radix key

table/destination.go, table/destination_test.go
In NewDestination we add additional path to AddrToRadixkey to check
the concrete type of nlri.
=> table: reduce allocs in NewDestination

gobgp/cmd/mrt.go, packet/mrt/mrt.go, packet/mrt/mrt_test.go
This patch enables to decode/encode MRT format with BGP routing information including the geographical location which described in RFC6397.
=> packet/mrt: BGP with Geo-Location Extensions (RFC6397)

config/bgp_configs.go, server/bmp.go, server/fsm.go, tools/pyang_plugins/gobgp.yang
This PR enables to send BMP statistics reports for the following types;
- Stat Type = 11: (32-bit Counter) Number of updates subjected to treat-as-withdraw treatment.
- Stat Type = 12: (32-bit Counter) Number of prefixes subjected to treat-as-withdraw treatment.
Note: Currently, this implementation considers only updates or prefixes received from neighbors, but not enough to follow the handling process described in RFC7606.
=> bmp: Support number of withdraw updates and prefixes

api/grpc_server.go, client/client.go, config/bgp_configs.go, config/default.go, config/serve.go, config/util.go, docs/sources/configuration.md, gobgp/cmd/common.go, gobgp/cmd/monitor.go, gobgp/cmd/neighbor.go, gobgpd/main.go, server/bmp.go, server/fsm.go, server/mrt.go, server/peer.go, server/server.go, server/server_test.go, table/destination.go, table/path.go, tools/pyang_plugins/gobgp.yang
This patch adds the Dynamic Neighbor feature.
The configuration syntax is like following:
```
[[dynamic-neighbors]]
[dynamic-neighbors.config]
prefix = "10.0.0.0/24"
peer-group = "my-peer-group"
```
(This patch updates #1289)
=> Support Dynamic Neighbor

config/default.go, server/peer.go, server/server.go
If State.NeighborAddress is not set, setting default configs
for the dynamic peers will fail. This patch sets State.NeighborAddress
before setting default configs.
And this avoids overwriting State.NeighborAddress if it is set.
This fixes #1283.
=> Fix Fails in Initializing Dynamic Peer

config/default.go, server/fsm.go, server/server.go, server/sockopt.go, server/sockopt_bsd.go, server/sockopt_linux.go, server/sockopt_openbsd.go, server/util.go
For the interoperability of TTL security, we need to set TTL before dialing and accepting connection to/from neighbors.
This patch fixes to set the default TTL(=255) for incoming connection, and set the given TTL for outgoing connection.
=> server: Set TTL before dialing for interoperability of TTL security

test/lib/base.py, test/scenario_test/addpath_test.py
This patch adds the test cases for the mixed situation of add-path enabled routers and non add-path enabled routers and advertising/withdrawing routes in such situation.
=> scenario_test/addpath_test: Test cases with non add-path router

config/bgp_configs_test.go, docs/sources/configuration.md
Currently, "docs/sources/configuration.md" has some obsoleted config parameters and some syntax errors.
This PR fixes these problems and introduces UT for validating syntax of the configuration example.
=> docs: Update config example

table/destination.go
With addpath support, two paths from API without AS_PATH attribute
could be compared.
=> table: disable wrong warning about aspath

gobgpd/main.go
alias "p" for "github.com/kr/pretty" collides the local variable "p" for Peer structure.
This patch fixes to avoid this name collision and also sorts the import order with goimports.
e.g.) goimports -w -local github.com/osrg/gobgp gobgpd/main.go
=> gobgpd: Avoid name collision

api/util.go, gobgp/cmd/mrt.go, table/adj.go, table/destination.go, table/destination_test.go, table/path.go, table/table.go, table/table_test.go
allocating 256 bytes per prefix isn't a good idea. Let's allocate 8
bytes by default and expand dynamically if necessary.
=> table: allocate bitmap for path id dynamically

server/rpki.go
I'd like to use addROA()/delROA() in my code as library. But currently they are not exportable.
I am happy if you could merge this.
=> server: export addROA()/delROA() for library usage

.travis.yml
travis-ci drops 1.7 support so needs to move on.
=> run go 1.9 for travis-ci instead of 1.7

api/grpc_server.go, config/bgp_configs.go, config/default.go, config/util.go, server/fsm.go, server/peer.go, server/server.go, tools/pyang_plugins/bgpyang2golang.py, tools/pyang_plugins/gobgp.yang
To reduce the translations of "AfiSafiName" into "bgp.RouteFamily", this
patch introduces "Family" field into "AfiSafiState" and stores the
translated value.
=> config: Introduce Family field into AfiSafiState

server/rpki.go, server/rpki_test.go
The second return value (bucket) in validatePath() is wrong and verbose. bucket has the last result of the function(fn) only. However the first return value (validation) includes its correct value.  So I think it's enough and we can delete it.
=> server: Remove the wrong and verbose return value in validatePath()

server/server.go
After Shutdown() is called, the main goroutine waits for peers'
goroutines to stop then dies. But if no peer is configured, the main
goroutines never dies.
=> server: stop Shutdown() with no peer

packet/bgp/bgp.go
Currently, the parsing results of flags in flowsspec filter
will be varied every time they are parsed.
For example, the tcp-flag '=UFP' may be represented to '=UPF' or '=PUF'
and so on.
This is due to the use of interation to map. Iterations over maps
does not happen in a consistent order.
This fixes it by iterating sorted slices instead of maps.
This fixes #1483.
=> packet/bgp: Avoid Varied Flag Representations in Flowspec Filter

server/peer.go, server/server.go
Currently, with iBGP peering, the CLI injected path will not be withdrawn
when the deletion if any other path exists on RIB, then the CLI injected
path will be left on iBGP peers even if the route is deleted on the
originator router.
This problem can cause routing loops in some case.
This patch fixes to withdraw the old best path when it was the CLI (or
gRPC) injected path.
=> server: Avoid local paths left on iBGP peers

config/default.go, config/util.go, server/peer.go, server/server.go, server/server_test.go
Currently, the config of PeerGroup members are not set properly.
For example, if LocalAs of the neighbor is not set in the config file,
LocalAs will be set to Global.As as a default value.
After this, however, if the neighbor is a member of a peer group,
LocalAs will be unexpectedly overwritten by the peer group config.
This commit fixes this by setting default values after
applying the peer group config.
Adding to this, this commit avoids unnecessary applying
the peer group config.
=> config: Properly set config of PeerGroup member

packet/bgp/bgp.go, packet/bgp/helper.go, packet/bgp/validate_test.go
This patch renames some variable names in snake case (e.g., "last_byte_value") to that in the camel case (e.g., "lastByte") because Go prefers the camel case for variable names.
This patch makes linter (a little) more happy.
=> packet/bgp: Rename snake case to camel case

server/server.go
=> server: adminDown operation wrongly resets State.PeerAs

config/default.go
The commit ab953211 prohibits the unconfigured peer ASN but it breaks
the unnumbered BGP feature. The old behavior needs to be reverted.
=> config: allow unconfigured peer ASN

gobgp/cmd/global.go, packet/bgp/bgp.go, packet/bgp/bgp_test.go, packet/bgp/constant.go, packet/bgp/validate_test.go, table/path.go
Currently, the parser for the string representation of FlowSpec rules splits the given string into characters and validates them character by character. So we need to handle the unexpected white spaces carefully.
This problem is related to https://github.com/osrg/gobgp/pull/1489.
This PR introduces the regular expressions to parse the FlowSpec rules and simplify the parser.
With these patches, the robustness for the unexpectedly inserted white spaces like "   &   ==   tcp   " will be improved.
Also, includes some improvements for the string representation of the FlowSpec rules.
Example:
- The NOT MATCH operand of "tcp-flags" is replace from "=!" to "!="
- The combined "fragment" value will be joined with "+" (e.g. "is-fragment+first-fragment")
FYI, I will update documents for the FlowSpec …
=> packet/bgp: Improve FlowSpec CLI argument format and string representation

gobgp/cmd/neighbor.go, server/server.go
This fixes the ae7e572550df919c1b9990da8787fc1e860bc20d commit
regression. gobgp neighbor command takes a bogus neighbor name like
the following:
fujita@ubuntu:~/go/src/github.com/osrg/gobgp/gobgp$ ./gobgp n 1
BGP neighbor is 172.17.0.2, remote AS 65001
BGP version 4, remote router ID unknown
BGP state = active, up for 17496d 14:21:50
BGP OutQ = 0, Flops = 0
Hold time is 0, keepalive interval is 0 seconds
Configured hold time is 60, keepalive interval is 20 seconds
=> cmd: fix getNeighbor() to take bogus neighbor name

test/lib/gobgp.py
For Unnumbered BGP, neighbor AS number isn't needed
to be specified, so 'peer-as' should not be specified
in the scenario test for Unnumbered BGP.
However, currently 'peer-as' is always specified
in test/lib/gobgp.py
This PR solves this by not specifying `peer-as`
if 'neighbor-interface' is configured.
=> test/lib: Allow unconfigured peer-as for Unnumbered BGP

packet/bgp/bgp.go, packet/bgp/bgp_test.go
MP_REACH_NLRI was already correctly encoded in JSON, while this was
not the case for MP_UNREACH_NLRI.
Before:
```json
"PathAttributes": [
{
"type": 15,
"value": "AAIBQCABDbgAEwAA"
}
]
```
After:
```json
"PathAttributes": [
{
"type": 15,
"afi": 2,
"value": [
{
"prefix": "2001:db8:8::/64"
}
],
"safi": 1
}
]
```
This commit also adds two tests not directly related to JSON encoding
as I was first thinking the problem may be related to incorrect
parsing of the path attribute.
=> packet/bgp: JSON encode of MP_UNREACH_NLRI attribute

test/scenario_test/bgp_unnumbered_test.py, test/scenario_test/run_all_tests.sh
On some environments, it's necessary to use the current PYTHONPATH to run python.
=> test: use the current PYTHONPATH in run_all_tests.sh

.travis.yml
Use the old images for now because seems that some tests always fail on the new image.
=> travis: use old Trusty images

table/message.go, table/message_test.go
On some conditions, we add some ASes to As4PathParam.AS but don't
update As4PathParam.Num (the number of ASes). It breaks serialization
of AS4PathParam.
Instead of modifying the internal of As4PathParam, let's create a new
As4PathParam object.
=> table: fix converting 2bytes to 4bytes AS PATH

test/scenario_test/addpath_test.py
When adding or deleting routes in ExaBGPContainer, it is required to restart ExaBGPContainer with the current implementation.
This patch fixes to wait for the re-establishment with ExaBGP and improves the stability of this test case.
=> addpath_test: Wait for re-establishment with ExaBGP

.travis.yml
Because "satori/go.uuid" changed some syntax of its API, "go fmt" and
"go vet" commands will fail with the latest codes.
This patch fixes to run dep ensure before running these tests and solves
this problem.
=> travis: Run "dep ensure" before "go fmt" and "go vet"

Gopkg.lock, Gopkg.toml, table/path.go
The API has changed with the master branch of go.uuid. GoBGP uses the
dependency management tool so it's not problem. However, there are
projects using GoBGP as a library and doesn't use a dependency
management tool...
GoBGP has used a released version of go.uuid so now I have to change
Gopkg.toml to use tha master branch.
=> fix breakage with the latest github.com/satori/go.uuid

server/server.go
close #1575
if L854 is executed before L924, we hit a crash because of closing a
channel twice. This fixes the isseu but We had better to refactor the
code to delete a peer.
=> server: fix dynamic neighbor crash

api/grpc_server.go, config/bgp_configs.go, server/server.go, table/destination.go, table/table_manager.go, tools/pyang_plugins/gobgp.yang
In some use-cases, the option to disable best path selection is useful to reduce the compute resource usage.
=> config: Option to disable best path selection

test/lib/exabgp.py, test/scenario_test/flow_spec_test.py, test/scenario_test/global_policy_test.py, test/scenario_test/route_server_as2_test.py, test/scenario_test/route_server_test2.py
This PR enhances test cases of scenario_test/flow_spec_test.py with using ExaBGP version 4.0.5.
With ExaBGP version 4.0.5, we can use "exabgpcli" command which enables ExaBGPContainer to add/delete routes without restarting ExaBGP daemon and get adj-RIB-{in,out}. Then, this PR extends the APIs of ExaBGPContainer using "exabgpcli" command.
=> scenario_test: FlowSpec with ExaBGP

packet/bgp/bgp.go, packet/bgp/bgp_test.go, packet/bgp/helper.go, packet/bgp/validate.go, table/destination.go, table/path.go
This PR removes "Value" field, which stores the raw decoded/serialized binary data, in order to reduce the memory usage.
Also implements some missing String()/MarshalJSON() functions.
=> packet/bgp: Remove raw binary field on PathAttribute struct

.travis.yml, README.md
drop 1.8 support also.
Note that ugly double quates are necessary
https://github.com/travis-ci/gimme/issues/132
=> add golang 1.10 support

gobgp/cmd/global.go, packet/bgp/bgp.go, packet/bgp/bgp_test.go
The other interface types in "packet/bgp" package have "Interface" suffix.
This patch fixes to follow this naming convention.
Golang's naming convention recommends to use "er" suffix though.
Also, this patch moves the AIGP TLVs definitions to the near of the PathAttributeAigp structure and defines NewAigpTLVDefault function.
=> packet/bgp: Rename AigpTLV to AigpTLVInterface

gobgp/cmd/global.go, packet/bgp/bgp.go, packet/bgp/helper.go
This PR flattens `OpaqueExtended` structure to improve the usability.
With the current implementation:
```go
var e bgp.ExtendedCommunityInterface
...
e = &bgp.OpaqueExtended{
IsTransitive: true,
SubType:      bgp.EC_SUBTYPE_ENCAPSULATION,
Value: &bgp.EncapExtended{
TunnelType: bgp.TUNNEL_TYPE_VXLAN,
},
}
```
With this PR:
```go
var e bgp.ExtendedCommunityInterface
...
e = &bgp.EncapExtended{
TunnelType: bgp.TUNNEL_TYPE_VXLAN,
}
```
or
```go
var e bgp.ExtendedCommunityInterface
...
e = bgp.NewEncapExtended(bgp.TUNNEL_TYPE_VXLAN)
```
Also, this PR include a fix of a typo and some improvements for `UnknownExtended`.
=> packet/bgp: Flatten structure of OpaqueExtended

docs/sources/getting-started.md
The way to install GoBGP is outdated. README tells how so let's remove.
Also bash completion scripts haven't be updated for long time so let's
remove too.
[ci skip]
=> docs: update gettting-started

packet/bgp/bgp.go, packet/bgp/bgp_test.go, packet/bgp/helper.go
The serialization of ipv4/v6 nlri should be goroutine-safe but somehow not.
=> packet/bgp: make serialization of ipv4/v6 nlri goroutine-safe

server/server.go
Currently, globalRib is always set to dynamic neighbors even if they are route server clients.
This patch fixes to set rsRib when the neighbor is a route server client.
This fixes #1622.
=> server/server: Set rsRib to RS client in adding dynamic neighbor

.travis.yml, server/server.go, test/scenario_test/rtc_test.py
Currently, even if RTM NLRIs are exchanged as expected, RT filter is not successfully applied on a Route Reflector. This patch fixes problem and registers the existing scenario test `rtc_test` to the Travis-CI tests.
=> RTC: Fix outgoing RT filter

table/path.go
When installing routes in a VRF the PathIdentifier is lost. This seems to be because we are replacing the `nlri` of the path with a new one that doesn't seem to maintain all the original attributes. This leads to the following situation:
```
Network              Next Hop             AS_PATH              Age        Attrs
11.0.0.0/24          1.1.1.1              3 4                  00:00:02   [{Origin: ?}]
```
As you can see even though the prefixes have different identifiers the first one is overwritten. This doesn't happen in the global rib:
```
Network              Next Hop             AS_PATH              Age        Attrs
*> 11.0.0.0/24          1.1.1.1              3 4                  00:00:08   [{Origin: ?}]
*  11.0.0.0/24          1.1.1.2              3 4                  00:00:02 …
```
=> Restore PathIdentifier for paths belonging to VRFs

zebra/zapi.go
Currently, it is not possible for a client of the zebra library to react to receive errors, e.g., when the far end closes the connection.
This simple fix allows a client to be notified about a receive error by closing the `incoming` channel.
=> Close incoming channel in zapi on receive error

contrib/centos/README.md, contrib/centos/add_gobgpd_account.sh, contrib/centos/gobgpd.service
This commit contains `systemd` unit file and the documentation
describing how to run `gobgp` as `systemd` managed service
on CentOS/RHEL Linux distribution.
Signed-off-by: Paul Greenberg <greenpau@outlook.com>
=> contrib: systemd unit files and docs

test/pip-requires.txt
Seems that fabric v2 doesn't work with the current files. Let's keep
using v1.X for now.
=> test: avoid fabric version 2.0

server/mrt.go
For reloading locally generated routes by using MRT dump file, this patch enables to include locally generated routes into TABLE_DUMPv2 records.
For the backward compatibility, this patch adds a new configure option "include-local" into "mrt-dump.config" section and please enable this option to include locally generated routes.
Configuration Example:
```toml
[[mrt-dump]]
[mrt-dump.config]
dump-type = "table"
file-name = "/tmp/table.dump"
dump-interval = 60
include-local = true
```
=> mrt: Enable to dump locally generated routes

test/lib/gobgp.py, test/scenario_test/graceful_restart_test.py, test/scenario_test/long_lived_graceful_restart_test.py, test/scenario_test/vrf_neighbor_test2.py
For the stability of some scenario tests, this PR fixes to wait for GoBGP starting up after restarting GoBGP daemon.
=> scenario_test: Wait for GoBGP starting up

server/server.go, test/scenario_test/rtc_test.py
Because the RTM is removed from adj-RIB-in before collecting the
candidate routes to be withdrawn, the candidates are unexpectedly
filtered before sending withdraw messages. Then on the peers, the VPN
routes are left on.
This patch fixes to selects candidates from the filtered paths and send
withdraw messages as expected. Also resolves the TODO in
"test/scenario_test/rtc_test.py".
=> server: Withdraw routes when received RTM withdrawal

gobgp/cmd/common.go
Adds a user-friendly error message on gRPC connection error.
Resolves: #1701
=> gobgp/cmd: add message gRPC connection error

server/server.go
We should do stricter validation. Probably, we should use
packet/bgp/validate.go.
close #1660
=> server: reject route without origin attribute via AddPath()

api/gobgp.proto
=> Fix: ruby client failed with "Enum value '_' does not start with an uppercase letter as is required for Ruby constants"

api/grpc_server.go, gobgp/cmd/policy.go, server/server_test.go, server/sockopt_darwin.go
Some staticcheck issues that were identified: 
```
~/gocode/src/github.com/osrg/gobgp/api/grpc_server.go:72:45: printf-style function with dynamic first argument and no further arguments should use print-style function instead
~/gocode/src/github.com/osrg/gobgp/gobgp/cmd/policy.go:68:34: printf-style function with dynamic first argument and no further arguments should use print-style function instead                         
~/gocode/src/github.com/osrg/gobgp/server/server_test.go:172:14: sleeping for 1 nanoseconds is probably a bug. Be explicit if it isn't: time.Sleep(time.Nanosecond)                                     
~/gocode/src/github.com/osrg/gobgp/server/sockopt_darwin.go:42:2: should check returned error before deferring fi.Close() …
```
=> simple staticcheck fixes

.travis.yml
Codecov will need to be given access to the repo. This will help understand the state of the codebase over time.
The example report and system can be found here: https://codecov.io/gh/jeffbean/gobgp
Also adding `megacheck` to help cleanup and ensure diffs and code stay clean. It fails with many errors but should not block PRs until we fix the current issues (a followup PR).
=> Adding travis config for Codecov 

cmd/gobgp/cmd/rpki_test.go
Sometimes fails due to listen port conflict with tests in
internal/pkg/client.
Using unix domain socket migth be a proper fix.
=> cmd/gobgp: use different grpc port for rpki_test

test/lib/bird.py, test/lib/gobgp.py, test/lib/quagga.py
This PR enable us to use container images which contain BusyBox for scenario test.
When we want to do scenario test with our own container image, for example which is based on alpine, we can specify own image like `GOBGP_IMAGE=my/image:tag ./run_all_tests.sh`.
=> scenario_test: Make BusyBox based container available

pkg/server/peer.go
llgrFamilies attempts to obtain a read lock on its own but the caller already
has one. This results in deadlock.
Addresses #1818
=> Release read lock before calling llgrFamilies

internal/pkg/apiutil/attribute.go, internal/pkg/apiutil/attribute_test.go
Fix error that GwAddress attr is missing in EVPNIPPrefixRoute.
Updated testcase.
=> api: add GwAddress to EVPNIPPrefixRoute

pkg/server/peer.go
introduced by 433440067d8084556a31ffd4b8bfa8671bfcaab2
Reported-by: Eiichiro Watanabe <a16tochjp@gmail.com>
=> server: fix deadlock regression

api/gobgp.pb.go, api/gobgp.proto, internal/pkg/config/util.go, pkg/server/grpc_server.go
Currently, `gobgp neighbor x.x.x.x enable/disable` command enables to control the peer.
However it doesn't work the same thing from config using `admin-down = true/false`. This PR will fix it.
=> Support AdminDown from config

cmd/gobgp/common.go, cmd/gobgp/root.go
timeout context is for only connecting. We should refactor the code to
avoid global context variant.
=> cmd/gobgp: don't use timeout context for requests

pkg/server/grpc_server.go
add anyNlri toPathApi when path.IsWithdraw, then we can GetExtCommunities when IsWithdraw
=> add anyNlri toPathApi when path.IsWithdraw

cmd/gobgp/common.go
This broke vet for me. Not sure why it didn't break in CI.
=> Add quotes to short option value

.travis.yml
The error message of 'go vet' goes to stderr so the length of the
stdout is zero. Always the test passes successfully.
'go vet' exits with non zero when something wrong happens.
=> travis: fix go vet

pkg/server/server.go
both assume that getBestFromLocal() returns filtered paths by policies
but it doesn't. Paths filtered by policies are returned as withdraw
paths.
=> server: fix handleRouteRefresh and softResetOut

README.md
Seems that bluemix.net is unstable nowadays.
=> README: use now.sh instead of bluemix.net for slackin

internal/pkg/table/policy.go
this error can be reproduced by:
gobgp p statement s1 add action as-prepend 65001 1
gobgp p add p1 s1
gobgp n 192.168.0.5 p import add p1
gobgp n 192.168.0.5 softresetin
then:
panic: runtime error: invalid memory address or nil pointer dereference
=> server: fix nil pointer error when apply policy

internal/pkg/zebra/zapi.go
I found a typo (LABLE->LABEL) in my source code zapi.go which was merged in mainstream
=> fix typo in zapi.go: LABLE -> LABEL

internal/pkg/table/path.go, pkg/server/grpc_server.go, pkg/server/server.go, pkg/server/server_test.go, pkg/server/zclient.go
- AddPath() with an api.Path object then DeletePath() works with the same api.Path object.
- ListPath() returns an api.Path object then DeletePath() works with the same api.Path object.
The above is guaranteed with and without PeerInfo (SourceAsn and SourceId).
fixes #1752
=> make Add/Delete/ListPath APIs symmetric

cmd/gobgp/neighbor.go
showNeighborRib() executes net.ParseCIDR() for vrf prefix like
10.100:100:10.0.0.0/24 and then crashes.
Probably ListRib() API should support an option to return sorted
destinations.
close #1942
=> gobgp: fix vrf rib command crash

cmd/gobgp/common.go, cmd/gobgp/neighbor.go
$ gobgp n 10.0.255.1 p
invalid policy type: choose from (in|import|export)
The in policy was removed long ago.
=> cmd/gobgp: remove in policy debris

README.md
This complements the commit 9d906149.
=> README: replace a remaining bluemix URL with now.sh

pkg/server/server.go
eor state was not reset during peer restarting, and after peer re-established, it will withdraw all stale routes as soon as first update is received regardless of eor
=> reset eor state on graceful-restart peer down

docs/sources/cli-command-syntax.md
`gobgp neighbor delete` doesn't work. We need to use `gobgp neighbor del`.
=> doc: fix "del" command for removing a neighbor

internal/pkg/table/path.go, internal/pkg/table/policy_test.go
Currently, GoBGP advertises Large Communities attributes with length of zero when all of them were removed by policy action. Here is a screenshot of a part of packet which was sent from GoBGP.
As described in [RFC7606 Section.4](https://tools.ietf.org/html/rfc7606#section-4), most of path attributes having length of zero shall be considered as syntax error. Actually, the above packet caused BGP peer shutdown due to attribute length error (Notification code 3/5).
This patch fix it by checking length of Large Communities and removing it (if necessary), the same as the way of Path.SetCommunities function.
=> table: fix to avoid setting vacant Large Communities

pkg/server/fsm.go, pkg/server/fsm_test.go, pkg/server/peer.go, pkg/server/server.go, pkg/server/server_test.go
Fixed a race bug that causes the unittest failure. Also fixed
StopBgp() to block until all the peers are deleted cleanly.
=> fix race of peer deletion

README.md
Seems that the mailing list is unpopular nowadays. Let's focus on
github and slack.
=> README: drop the mailing list

internal/pkg/zebra/zapi_test.go
syscall.AF_INET/AF_INET6 are os/architecture specific. On some non
Linux x86 architectures, failures like the following happen:
--- FAIL: Test_NexthopRegisterBody (0.00s)
Error Trace:    zapi_test.go:893
Error:			Not equal: 0x1e (expected)
!= 0xa (actual)
Error Trace:    zapi_test.go:894
Error:			Not equal: net.IP{0x20, 0x1, 0xd, 0xb8, 0x0, 0x1, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1} (expected)
!= net.IP(nil) (actual)
Diff:
--- Expected
+++ Actual
@@ -1,2 +1,2 @@
-(net.IP) (len=16 cap=16) 2001:db8:1:1::1
+(net.IP) <nil>
looks like that frr uses os/os/architecture specific values in the
zapi message.
=> zebra: fix unit test failure on non linux

cmd/gobgp/neighbor.go
Hi,
so basically - if gobgpd is started with TLS support, but `--tls ...` is not passed to the cli, it crashes when listing neighbors with a segfault due to an unhandled error.
=> Fix cli crash when showing neighbor stats as list.

docs/sources/rpki.md
Long ago gobgp stored the validation results in memory but for reduce
memory usage, the cache was removed. Currently, every time you request
the validation result, gobgp validates paths with the latest ROAs.
=> docs: remove obsolete rpki command

.travis.yml
sometimes the unittest fails due to 120s timeout. The travis-ci might
be overloaded? Let's see what happens with the longer timeout.
=> travis: use longer timeout

internal/pkg/table/path.go, pkg/server/peer.go, pkg/server/server.go
#2073 
Added support for ipv4/ipv6-flowspec announcements/withdraws when a neighbor is configured in a vrf.
=> Support ipv4-flowspec for VRF enslaved neighbor

docs/sources/grpc-client.md
Closes: #2095.
We need to specify another include path.
Signed-off-by: George Melikov <g.melikov@corp.mail.ru>
=> gRPC docs: include all needed paths

internal/pkg/config/default.go
This fixes a bug that the duplicated AFI is configured with the peer
group. OverwriteNeighborConfigWithPeerGroup() appends the peer group's
AFI configuration to the existing one instead overwriting.
=> fix PeerGroup AFI handling

pkg/server/server.go, pkg/server/server_test.go
DeletePath() doesn't delete the entry of the map for UUID.
=> server: fix DeletePath() memory leak

internal/pkg/table/adj.go, internal/pkg/table/table_manager.go, pkg/server/peer.go, pkg/server/server.go
when a peer is down, use paths in its adj table instead of searching
for the global table.
=> table: kill GetPathListByPeer()

docs/sources/bgp-confederation.md
Fix #2146
This pull request adds documentation for BGP Confederation, a feature which allows multiple ASNs to be composed to act as though they are a single autonomous system.
Currently, I believe I have the initial configuration piece here. I was wondering if you had a specific program you use or design you prefer for topology diagrams and if you had a suggestion for how to add verification to this.
=> Add BGP Confederation documentation

docs/sources/bgp-confederation.md
Sorry about this, I had forgot that TOML subtables require the name of the parent table in their path's. I've validated this configuration:
```
root@kkirsche-dev:/home/kkirsche# ./gobgpd -f config.toml
{"level":"info","msg":"gobgpd started","time":"2019-08-28T18:32:23Z"}
{"Topic":"Config","level":"info","msg":"Finished reading the config file","time":"2019-08-28T18:32:23Z"}
{"level":"info","msg":"Peer 10.0.0.2 is added","time":"2019-08-28T18:32:23Z"}
{"Topic":"Peer","level":"info","msg":"Add a peer configuration for:10.0.0.2","time":"2019-08-28T18:32:23Z"}
```
```
root@kkirsche-dev:# cat config.toml
[global]
[global.config]
as = 65001
router-id = "10.0.0.1"
[global.confederation.config]
enabled = true
identifier = 30
member-as-list = [ 65002 ]
```
=> Fix error in BGP Confederation syntax

.github/workflows/release.yml
https://github.community/t5/GitHub-API-Development-and/How-to-restrict-execution-of-GitHub-Actions-workflow-on-tags/td-p/29567
'tags' doesn't work; the action is executed when anything (tag,
branch, etc) is created. Let's work around.
=> github: workaround for action trigger bug

cmd/gobgp/mrt.go
Overwrite only the nexthop attribute and not all attributes
Signed-off-by: Amit Nishry <amit.nishry@gmail.com>
=> Fix nexhop overwrite with gobgp mrt inject --no-ipv6 --nexthop x.x.x.x

go.mod, internal/pkg/table/policy.go, pkg/server/server.go
currently, validate is executed even if the result is not necessary.
=> execute rpki validation for policy only when it's necessary

internal/pkg/table/policy.go
This fixes a pre-compiled pattern for SingleAsPathMatch though this didn't affect actual behavior much because it always fails and falls back to a regexp match against an AS Path text representation.
=> table: fix SingleAsPathMatch pre compiled pattern

pkg/server/server.go, pkg/server/server_test.go, pkg/server/zclient.go, test/scenario_test/zapi_v3_test.py
Fixes missing route propagation to proper vrfs in zapi when we have route import/export from different RTs
=> Maintain unique vrf IDs in watchEventBestPath vrf map

docs/sources/bmp.md
gobgmp was removed long ago. Add a pointer to other BMP server
implementations.
=> docs: update bmp verification section

internal/pkg/table/policy.go, pkg/server/server.go
The Reset method was difficult to understand. The reason is that it
was called in three different ways and did different things in each
case. It is easier to read when the three different modes are each
their own method.
This came up as I was looking deeper into the threading model around
policies. I think this change makes it easier to understand the code.
=> Split Reset into three methods

.travis.yml, go.mod, go.sum
Needs to update staticcheck for go 1.13.
=> travis: update go to 1.13

internal/pkg/apiutil/attribute_test.go, internal/pkg/apiutil/capability_test.go
When regenerating the `*.pb.go` file, we get many tests failing
because testify is using `reflect.DeepEqual()` under the hood. There
is no option to have a custom comparison function and currently, the
only way around is to use `proto.Equal()` to compare protobuf
messages. The downside of using `proto.Equal()` is that we loose the
expected/actual display in case of a mismatch.
When comparing family, we compare `Api`/`Sapi` in separate asserts
instead of using `proto.Equal()`.
Fix: #1952
If you prefer to keep the more descriptive error messages, I can also maintain the patch myself for Debian use. Hopefully, testify will come with a better solution in the future.
=> tests: fix failing tests when using more recent versions of protobuf

.travis.yml
The ipv6 support of the newer versions works differently. Stick to
17.03 for a while.
=> travis: use docker 17.03

pkg/packet/bgp/bgp.go, pkg/packet/bgp/constant.go, pkg/packet/bgp/validate.go
* optimized comparision of LargeCommunities: it compared strings, now it compares uint32 values. I hadn't replaced O(n^2) comparision due to unlikeliness of a significant length of this list.
* got rid of possible double type cast in `ValidateUpdateMsg()`
* used preallocation in `BitmaskFlagOp.String()`
* fixed misspell
=> optimized allocations in packet/bgp validations

internal/pkg/apiutil/attribute.go
Signed-off-by: Serguei Bezverkhi <sbezverk@cisco.com>
Currently if ipv6 next hop is specified, 
```
a2, _ := ptypes.MarshalAny(&api.NextHopAttribute{
NextHop: "2001:222:1111:20::201",
})
```
AddPath fails with the following error:
```
rpc error: code = Unknown desc = invalid nexthop address: 2001:222:1111:20::201
```
This PR adds missing code to handle ipv6 next hop properly.
=> fix ipv6 next hop

.env, test/scenario_test/addpath_test.py, test/scenario_test/aspath_test.py, test/scenario_test/bgp_confederation_test.py, test/scenario_test/bgp_malformed_msg_handling_test.py, test/scenario_test/bgp_router_test.py, test/scenario_test/bgp_unnumbered_test.py, test/scenario_test/bgp_zebra_nht_test.py, test/scenario_test/bgp_zebra_test.py, test/scenario_test/evpn_test.py, test/scenario_test/flow_spec_test.py, test/scenario_test/global_policy_test.py, test/scenario_test/graceful_restart_test.py, test/scenario_test/ibgp_router_test.py, test/scenario_test/long_lived_graceful_restart_test.py, test/scenario_test/route_reflector_test.py, test/scenario_test/route_server_as2_test.py, test/scenario_test/route_server_ipv4_v6_test.py, test/scenario_test/route_server_malformed_test.py, test/scenario_test/route_server_policy_grpc_test.py, test/scenario_test/route_server_policy_test.py, test/scenario_test/route_server_softreset_test.py, test/scenario_test/route_server_test.py, test/scenario_test/route_server_test2.py, test/scenario_test/rtc_test.py, test/scenario_test/vrf_neighbor_test.py, test/scenario_test/vrf_neighbor_test2.py, test/scenario_test/zapi_v3_multipath_test.py, test/scenario_test/zapi_v3_test.py
added `.env` file for vscode to find test/lib module
replace `is not` exp in *_test.py files to suppress python syntax warning with py3
=> chore: general py setting for vscode development; suppress py3 syntax warnings in py test files

pkg/server/server.go
When a dynamic neighbor/peer is deleted (i.e. BGP session goes down), its incoming channel is closed, but never removed from the server's list. This results in excessive iterations of the loop in BgpServer.Serve func, as it constantly selects on the closed channel. This in turn causes **very** high CPU utilization, mainly from the repeated creation and garbage collection of the slice being passed to reflect.Select.
This PR fixes the issue by removing the incoming channel from the server's list when the dynamic neighbor is deleted (which also mirrors the behaviour of when a non-dynamic peer is deleted)
=> remove incomingCh when deleting dynamic peer

cmd/gobgp/policy.go
```
╰─$ gobgp policy nei del ns2                                                                                                                                                                                                                         2 ↵
panic: runtime error: slice bounds out of range [1:0]
goroutine 1 [running]:
main.parseNeighborSet(0xc000092660, 0x1, 0x1, 0x2, 0xc0000a4ea0, 0x0)
/Users/ij0151/go/src/github.com/osrg/gobgp/cmd/gobgp/policy.go:326 +0x70f
main.parseDefinedSet(0x1749b4c, 0x8, 0xc000092660, 0x1, 0x1, 0x174a070, 0xc0001d5d38, 0xc0000a4ea0)
/Users/ij0151/go/src/github.com/osrg/gobgp/cmd/gobgp/policy.go:429 +0x205
main.modDefinedSet(0x1749b4c, 0x8, 0x1745750, 0x3, 0xc000092660, 0x1, 0x1, 0x0, 0xc000096050) …
```
=> bugfix: fix a panic when delete neighborset (all) by name directly

README.md
It shows the status of slackin web server. We don't need it anymore.
=> README: remove slack status

pkg/server/server.go, pkg/server/server_test.go
fix ListPolicyAssignment() return an assignment response even if the
response doesn't have any policy. The assignment has default action
policy so it's useful without any policy.
=> server: fix ListPolicyAssignment to handle empty policy

test/lib/fabfile.py
Build GoBGP binaries of a pull request locally and copy them to the
container to be tested instead of copying the code into the container
and building the binaries inside.
=> make CI faster

.github/workflows/ci.yml
No need to use 16.04 for some.
=> ci: use ubuntu 18.04 for all jobs

cmd/gobgp/neighbor.go
I found this bug when I run the command gobgp vrf <vrf name> neighbor, it just show all neighbor without filtering vrf.
=> fix wrong vrf neighbors display

pkg/packet/bgp/bgp.go
Signed-off-by: Serguei Bezverkhi <sbezverk@cisco.com>
This PR fixes an interoperability issue reported. Original behaviour was not to set BoS on the label stack if Prefix SID attribute was present, the new behaviour is to set BoS.
=> Restore Setting BoS on TX

internal/pkg/table/path.go, internal/pkg/table/path_test.go, internal/pkg/table/policy.go, internal/pkg/table/policy_test.go
This change is required because currently GoBGP does not apply prefix filters to IPv6-labeled and IPv4-labeled prefixes. Instead, it simply blocks such prefixes from reaching the global RIB if a prefix set is specified in the policy. This issue has been raised for GoBGP before for IPv4 VPN prefixes (https://github.com/osrg/gobgp/issues/2115), although this change doesn't address that particular issue.
This change solves the problem by fixing `nlriToIPNet` to handle IPv4 and IPv6 labeled prefixes correctly, adding unit tests for it in the process. It also modifies the `Evaluate` function for `PrefixCondition` to initially return false based only on different AFIs rather than the AFI-SAFI pair.
=> Enable IPv6 and IPv4 labeled prefixes to match against prefix set in policy

internal/pkg/table/table.go, internal/pkg/table/table_test.go
probably regression due to the introduction of critbitgo.
=> table: fix longer-prefixes lookup

internal/pkg/config/util.go
Previously the LocalAs setting for the neighbor was ignored when
determining if the session is eBGP or not.
=> Fix IsEBGPPeer check to use LocalAs

pkg/packet/bmp/bmp.go
=> Fix ParseValue's bug for BMPStatsTLV32 in pkg/packet/bmp/bmp.go

.goreleaser.yml
- Use tags=netgo to ensure net package won't use cgo
- Rebuild stdlib (go build -a) to really disable cgo as it was
tried in https://github.com/osrg/gobgp/pull/2300
- Remove static ldflags as it would statically compile cgo
=> goreleaser: improve portability

tools/completion/gobgp-completion.bash, tools/completion/gobgp-dynamic-completion.bash, tools/completion/gobgp-static-completion.bash
They are not expected to be executed. This seems a silly path, but
some people bother filing bug reports about it, so if you are OK with
it, it could be "fixed".
=> tools: don't use a shebang for bash completion

pkg/packet/bgp/bgp.go
Added new MPLS TunnelType 'GENEVE' using the value defined in https://www.iana.org/assignments/bgp-tunnel-encapsulation/bgp-tunnel-encapsulation.xhtml#tunnel-types
=> Add GENEVE encapsulation support

internal/pkg/zebra/zapi.go
In general the writer should close the channel, thus we can close the channel here directly.
If zebra has disconnected the `closeChannel` method will in most cases not even close the channel
because no more messages can be received on it.
=> zebra: close the incoming channel

pkg/packet/bgp/bgp.go, pkg/packet/bgp/bgp_test.go
The capabilities' DecodeFromBytes() was eating as much data as given,
while these functions would normally be called with all the data
remaining to parse - e.g. including following capabilities.
Fixes osrg/gobgp#2399
=> Fix extended-nexthop & add-path capability parsing.

pkg/packet/bgp/bgp.go, pkg/packet/bgp/bgp_test.go
Signed-off-by: Matt Layher <mlayher@fastly.com>
Resolves a data race regarding the use of path identifiers:
```
==================
WARNING: DATA RACE
Write at 0x00c0004ddc84 by goroutine 41:
github.com/osrg/gobgp/pkg/packet/bgp.(*PrefixDefault).SetPathLocalIdentifier()
/project/vendor/github.com/osrg/gobgp/pkg/packet/bgp/bgp.go:1243 +0x36
github.com/osrg/gobgp/pkg/packet/bgp.(*IPv6AddrPrefix).SetPathLocalIdentifier()
<autogenerated>:1 +0x44
github.com/osrg/gobgp/internal/pkg/table.(*Destination).explicitWithdraw()
/project/vendor/github.com/osrg/gobgp/internal/pkg/table/destination.go:299 +0x688
github.com/osrg/gobgp/internal/pkg/table.(*Destination).Calculate()
/project/vendor/github.com/osrg/gobgp/internal/pkg/table/destination.go:237 +0xf2 …
```
=> pkg/packet/bgp: add mutex to PrefixDefault to avoid data race

.github/workflows/release.yml
https://github.com/goreleaser/goreleaser-action#workflow
This simplifies the workflow, allows to define the golang version it is
built with
=> .github/release: Use goreleaser action

pkg/packet/bmp/bmp.go
Hello!
This PR is related to the issue https://github.com/osrg/gobgp/issues/2122 . But generally, if there is an error during parsing of a BMP message, I should follow the `ErrorHandling` "instructions" on how to handle the error. In this case, the policy is `ERROR_HANDLING_TREAT_AS_WITHDRAW`. So, if I understand the RFC correctly (see https://datatracker.ietf.org/doc/html/rfc7606#section-2 ), I should treat all `BGPUpdate.NLRI` same as if they were in `BGPUpdate.WithdrawnRoutes`. But the issue is that on any error I don't receive the update message when using the `ParseBMPMessage` function, as any error causes the function to return `nil` for the message.
Maybe instead of `if msg.Header.Type == BMP_MSG_ROUTE_MONITORING {` I should check the error type and if it's `*bgp.MessageError`, …
=> Pass BGPUpdate message even on error

internal/pkg/table/table_manager.go
keep receiver name the same, it's more readable for IDE.
=> table: keep receiver name the same

cmd/gobgpd/main.go, pkg/server/server.go
This doesn't matter when you use TCP for API server, but when you use UNIX socket then the "forced" shutdown of the gRPC server causes the socket to be left behind, preventing the GoBGP server to start again.
```
$ ls -l api.sock
ls: cannot access 'api.sock': No such file or directory
$ go run ./cmd/gobgpd --api-hosts=unix://api.sock >/dev/null &
[1] 144472
$ ls -l api.sock
srwxrwxr-x 1 grongor grongor 0 lis 16 14:36 api.sock
$ killall -e gobgpd
[1]  + 144472 done       go run ./cmd/gobgpd --api-hosts=unix://api.sock > /dev/null                                                                         
$ ls -l api.sock   
srwxrwxr-x 1 grongor grongor 0 lis 16 14:36 api.sock
$ go run ./cmd/gobgpd --api-hosts=unix://api.sock             
{"level":"info","msg":"gobgpd …
```
=> Stop gRPC server when stopping GoBGP server

.github/workflows/ci.yml, .golangci.yml, cmd/gobgp/global.go, cmd/gobgp/neighbor.go, internal/pkg/table/policy_test.go, internal/pkg/zebra/zapi.go, internal/pkg/zebra/zapi_test.go, pkg/config/config.go, pkg/config/config_test.go, tools/config/example_toml.go
golangci-lint includes staticcheck (https://github.com/golangci/golangci-lint/blob/master/pkg/golinters/staticcheck.go) and provides more features that help to improve the code.
Current output:
```
internal/pkg/zebra/zapi.go:44:2: `maxPathNum` is unused (deadcode)
maxPathNum              = 64
^
internal/pkg/zebra/zapi.go:980:2: `zapi4MessageTag` is unused (deadcode)
zapi4MessageTag      MessageFlag = 0x10
^
internal/pkg/zebra/zapi.go:982:2: `zapi4MessageSRCPFX` is unused (deadcode)
zapi4MessageSRCPFX   MessageFlag = 0x40
^
internal/pkg/zebra/zapi.go:1962:2: `zapiNexthopFlagOnlink` is unused (deadcode)
zapiNexthopFlagOnlink    uint8 = 0x01 // frr7.1, 7.2, 7.3, 7.4, 7.5
^
internal/pkg/zebra/zapi.go:1305:13: Error return value of `c.SendHello` is not checked (errcheck)
c.SendHello()
^ …
```
=> .github/ci: Replace staticcheck with golangci-lint

.github/workflows/ci.yml, pkg/server/server.go
- don't try to unset md5 even if it wasn't set.
- don't warn when a listen socket is shutdown properly
=> server: silence bogus warning on sockets

pkg/server/server.go
gobgp rpki server command hasn't been working correctly since #a40bc53.
This code will fix it.
=> server: fix output of gobgp rpki server

pkg/server/bmp.go, pkg/server/server.go
fixed the following bug. With bmp established, adding a peer config
leads to this. Adding a peer config should not send bmp peer message.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa41c0a]
goroutine 36 [running]:
github.com/osrg/gobgp/v3/pkg/server.bmpPeerDown(0xc00032c370, 0x18, 0x0, 0xc00040cc78)
/home/ubuntu/git/gobgp/pkg/server/bmp.go:296 +0x10a
github.com/osrg/gobgp/v3/pkg/server.(*bmpClient).loop.func1(0xc00037f0e0, 0xc000416000)
/home/ubuntu/git/gobgp/pkg/server/bmp.go:228 +0xe65
github.com/osrg/gobgp/v3/pkg/server.(*bmpClient).loop(0x0)
/home/ubuntu/git/gobgp/pkg/server/bmp.go:265 +0x85
created by github.com/osrg/gobgp/v3/pkg/server.(*bmpClientManager).addServer …
=> server: fix bmp crash

pkg/server/server.go
needs to call the internal watch() API before creating goroutine
rather than calling it inside goroutine. We don't miss events.
=> server: fix WatchEvent API delay

internal/pkg/table/path.go, pkg/server/server_test.go
ToLocal() is used to copy Path in rib for advertising/exporting via
API (like ListPath). Needs to copy PathId.
=> table: fix Path ToLocal() to set PathId

go.mod
found a missing dep `go-cmp` in `go.mod`
the package is being used in `server_test.go`
=> chore: added missing dep

internal/pkg/table/path.go, internal/pkg/table/path_test.go, internal/pkg/table/policy_test.go
Fixes #2527, vpn routes can be filetred with match-sets.
=> Enable match-prefix-set policy for vpnv4/vpnv6 prefixes

pkg/packet/bgp/bgp.go
Formatting PathAttributeUnknown binary value as a string breaks text
output and may cause data truncation while line-by-line parsing.
Signed-off-by: Vladislav Grishenko <themiron@yandex-team.ru>
=> pkg/packet/bgp: fix PathAttributeUnknown output format

internal/pkg/table/policy.go
It saves a lot of resources when there is a lot of communities to match against,
say hundreds of RTs. The same approach is used in some other conditions,
ex. AsPathCondition.
=> optimised ExtCommunityCondition.Evaluate() by caching community string

pkg/server/grpc_server.go, pkg/server/server_test.go
Fixes the problem described in https://github.com/osrg/gobgp/issues/2541
I also added some simple test cases to make ensure the scenario described in this issue are covered in `AddPath` and `DeletePath` tests.
=> Fix AddPath IPv6 injected routes not honoring PathIdentifier

internal/pkg/config/bgp_configs.go, internal/pkg/config/util.go, pkg/server/fsm.go, pkg/server/grpc_server.go, tools/pyang_plugins/gobgp.yang
It allows to have more control on the connection established to peers by GoBGP. 
In my use case, I have an access list mechanism for incoming packets. Knowing the port in advance allows to accept the packets corresponding to a given BGP peering session. If I cannot set the port before initiating the connection, I would have to learn it dynamically, but that means dropping the first return packets from the remote peer (SYN+ACK), which is pretty ugly and unpredictable.
=> Add the possibility to choose the local port in the TCP connection to a peer.

internal/pkg/table/path.go, internal/pkg/table/table.go
Fixes issue outlined in https://github.com/osrg/gobgp/issues/2555
=> Fix panic in table.GetLongerPrefixDestinations() with invalid cidr

cmd/gobgp/global.go
A port is in the range 0..64k, not -32k..32k. Hence unsigned.
=> fix(cmd/gobgp): parse listen-port as u16, not i16

.github/workflows/ci.yml
ubuntu-18.04 is deprecated. Moreover, the shipped versions for pip
does not know how to handle Python's cryptography correctly. Let's
check if it works with ubuntu-20.04.
=> ci: use ubuntu-20.04

pkg/packet/bmp/bmp.go, pkg/packet/bmp/bmp_test.go
`ParseBody()` and `Serialize()` need to be aware if we Add-Path is
enabled to be able to parse/serialize BGP updates correctly.
This solves only half of the problem: server/bmp also needs to be
updated.
=> packet/bmp: enable parsing/serializing add-path-enabled BGP updates

cmd/gobgp/neighbor.go, docs/sources/cli-command-syntax.md
If anything else needs to be done, please let me know :)
```
➜  gobgp ✗ ./gobgp neighbor add 192.168.1.1 as 555 local-as 111
➜  gobgp ✗ ./gobgp neighbor -j | jq ."[0]"."conf"              
{
"local_asn": 111,
"neighbor_address": "192.168.1.1",
"peer_asn": 555,
"type": 1
}
➜  gobgp ✗ ./gobgp neighbor update 192.168.1.1 local-as 1994                 
➜  gobgp ✗ ./gobgp neighbor -j | jq ."[0]"."conf"           
{
"local_asn": 1994,
"neighbor_address": "192.168.1.1",
"peer_asn": 555,
"type": 1
}
```
Solves issue: https://github.com/osrg/gobgp/issues/2385
=> cli: Add `local-as` attribute in neighbor cmd

pkg/server/grpc_server.go, pkg/server/server.go
The context used there was a background context, which was not inherited from the stream. Thus when the client ends the stream (e.g. ^C `gobgp monitor global rib`), the context never completed, preventing the stop of most goroutines responsible for forwarding events. The only case where it completes is when an event gets generated, the transmit channel was closed, ending the chain of goroutines.
Fix by inheriting the context from the stream, which completes when the stream ends, properly cleaning up all resources.
1. Start gobgp
2. Observe the goroutine count using the pprof http server
3. Run and stop multiple `gobgp monitor global rib` and observe the goroutine count go up
Using the pprof interfaces also confirms that all the leaky goroutines are just parked and not doing anything.
=> grpc: fix goroutine leak in `WatchEvent`

cmd/gobgp/neighbor.go, internal/pkg/table/table.go, pkg/packet/bgp/mup.go
- [mup: fix route key for Type 1 ST Route](https://github.com/osrg/gobgp/commit/411667d052c0ea2a8ba095da7cc764371fde86dd)
- Removed TEID, QFI and Endpoint from route key to I-D compliant.
- [cli,mup: show TEID,QFI,Endpoint for Type 1 ST Route](https://github.com/osrg/gobgp/commit/82b708a95440ccf8052316b2ea08a7e5ffe5cdbf)
- [cli,mup: add support for filtering MUP routes with route type](https://github.com/osrg/gobgp/commit/dc328dccf667d2a5331ef764dfed02ca845fc784)
=> mup: fix route key for Type 1 ST Route

pkg/packet/bgp/mup.go
Current  code broke received data because it adds bytes to received data.
=> packet/bgp,mup: fix decode Interwork Segment Discovery route

pkg/packet/bgp/bgp.go
Using fmt.Sprintf adds additional time for getting string representation of each prefix and each attribute.
This PR replaces fmt.Sprintf with concatenation on some structs.
Synthetic benchmark shows x2 speed up:
```
type MockPrefix struct {
Prefix net.IP
Labels []uint32
RD     string
}
var TestPrefix = &MockPrefix{
Prefix: net.ParseIP("10.11.12.13"),
Labels: []uint32{1234},
RD:     "65534:1",
}
func Fmt(m *MockPrefix) string {
masklen := 32 - uint8(8*(len(m.Labels)+len(m.RD))) // useless test-only mask
return fmt.Sprintf("%s/%d", m.Prefix, masklen)
}
func Concat(m *MockPrefix) string {
masklen := 32 - uint8(8*(len(m.Labels)+len(m.RD))) // useless test-only mask
return m.Prefix.String() + "/" + strconv.FormatUint(uint64(masklen), 10)
}
func BenchmarkFmt(b *testing.B) {
for i := 0; i < b.N; …
```
=> Concat instead of fmt.Sprintf

pkg/packet/bgp/mup.go, pkg/packet/bgp/mup_test.go
https://www.ietf.org/archive/id/draft-mpmz-bess-mup-safi-01.html#section-3.1.3
The Prefix field must be encoded as described in RFC4271 4.3. UPDATE Message Format.
https://www.rfc-editor.org/rfc/rfc4271.html#section-4.3
The attached image is fixed UPDATE message.
=> packet/bgp,mup: fix prefix format in Type 1 ST route

tools/pyang_plugins/gobgp.yang
I forgot to use the YANG definition to generate bgp_configs.go.
=> pyang_plugins: add MUP SAFI to YANG definition

go.mod, go.sum, pkg/server/sockopt_linux.go, pkg/server/sockopt_linux_test.go
Use the TCPMD5Sig type and the corresponding SetsockoptTCPMD5Sig func added upstream in golang.org/x/sys v0.6.0
=> server: use SetsockoptTCPMD5Sig from golang.org/x/sys/unix

cmd/gobgp/common.go, cmd/gobgp/root.go, cmd/gobgpd/main.go
This PR addresses https://github.com/osrg/gobgp/issues/2066#issuecomment-640789765 by implementing authentication of API clients using TLS on top of the existing server authentication, effectively turning authentication mutual.
Implemented with this PR are:
- New command line flags `tls-client-cert-file` and `tls-client-key-file` for the `gobgp` binary. These flags are both respectively paths and in combination enable TLS client authentication against the gRPC API.
- New command line flag `tls-client-ca-file` for the `gobgpd` binary. If this path is set, it is loaded as a CA certificate against which clients are required to authenticate.
This would allow for gobgp's API to be used in a safe way from external clients. Use cases could include managing routes using a separately implemented …
=> Implement TLS client authentication

.github/workflows/ci.yml, .github/workflows/release.yml
- actions/setup-go@v4
- goreleaser/goreleaser-action@v4
- --rm-dist has been deprecated in favor of --clean
- https://goreleaser.com/deprecations/#-rm-dist
=> ci: update actions

cmd/gobgp/neighbor.go, internal/pkg/table/table.go
This PR enables to use `<prefix>` as not only route type but also route key.
=> cli,mup: fix prefix and route type handling

cmd/gobgp/neighbor.go, internal/pkg/config/util.go
Hello!
I hope you're doing well.
Thank you so much for your hard work in maintaining GoBGP.
Some of our customers have quite complicated setups with different local ASNs numbers, for example:
```
[global.config]
as = 65001
router-id = "11.22.33.44"
port = 179
[[neighbors]]
[neighbors.config]
neighbor-address = "22.33.44.55"
local-as = 65444
peer-as = 65001
[[neighbors.afi-safis]]
[neighbors.afi-safis.config]
afi-safi-name = "ipv4-unicast"
[neighbors.transport.config]
local-address = "11.22.33.44"
[[neighbors]]
[neighbors.config]
neighbor-address = "77.77.77.77"
local-as = 65333
peer-as = 56000
[[neighbors.afi-safis]]
[neighbors.afi-safis.config]
afi-safi-name = "ipv4-unicast"
[neighbors.transport.config]
local-address = "33.33.44.55"
``` 
Unfortunately, gobgp neighbor command does not …
=> Added local ASN and local BGP peering address for gobgp neighbor command

cmd/gobgpd/main.go, go.mod, pkg/config/config.go, pkg/server/grpc_server.go, pkg/server/rpki.go
Use Go's standard library `context` package instead of the `golang.org/x/net/context` package. Package `context has been available in the standard library since Go 1.7 and `x/net/context.Context` is merely an alias for the standard library type.
=> Use standard library context package

cmd/gobgp/global.go, pkg/packet/bgp/bgp.go
We implemented an option adding the BGP-LS NLRI to the gobgp command.   
This implementation is interoperable with Cisco XRd and Juniper cRPD.    
gobgp command:
``` bash
gobgp global rib add -a ls link bgp identifier 0 local-asn 65002 local-bgp-ls-id 0 local-bgp-router-id 2.2.2.2 local-bgp-confederation-member 1 remote-asn 65001 remote-bgp-ls-id 0 remote-bgp-router-id 1.1.1.1 remote
-bgp-confederation-member 0 ipv4-interface-address 10.0.0.2 ipv4-neighbor-address 10.0.0.1 sid 1000002 sid-type node v-flag l-flag b-flag p-flag weight 1 ipv6-interface-address fd00::1 ipv6-neighbor-address fd00::2
```
BGP-LS options can specified with `-a ls`.
- NLRI type: `node`/`link`
- Protocol ID: Only bgp is implemented
- paramSingle options: `identifier`/`local-asn`/`local-bgp-ls-id`/`local-bgp-router-i …
=> Add option to register BGP-LS NLRI in gobgp command

internal/pkg/config/util.go
This PR allows changing `EbgpMultihop` configuration via `UpdatePeer` RPC.
Before this change the `EbgpMultihop` changes are ignored in `UpdatePeer` and old configuration remains in place.
As TTL is configured via socket options at connect, we need to reconnect if it is updated.
=> Allow EbgpMultihop change in UpdatePeer

internal/pkg/config/util.go
Exposing PeerRestartTime and PeerRestarting info in config.NewPeerFromConfigStruct.
=> graceful-restart: expose peer graceful restart state information via API

internal/pkg/config/util.go, pkg/server/fsm.go, pkg/server/server.go
This PR allows non-disruptive (not causing connection reset) changes of TTL on BGP peer connections via neighbor's `EbgpMultihop` or `TtlSecurity` config in the `UpdatePeer` RPC.
It enhances my previous PR https://github.com/osrg/gobgp/pull/2658 where `EbgpMultihop` change in `UpdatePeer` was enabled, but required connection reset. This one also allows `TtlSecurity` change in the `UpdatePeer` RPC.
=> Allow non-disruptive changes of TTL in UpdatePeer

pkg/server/server.go
This fixes a bug introduced by my previous PR: https://github.com/osrg/gobgp/pull/2661
Avoids attempt to set TTL on a nil connection in `updateNeighbor`.
This can happen e.g. if `UpdatePeer` comes very quickly after `AddPeer` and the connection is not yet created.
=> Fix setting of TTL on a nil connection in updateNeighbor

internal/pkg/table/message.go, pkg/server/fsm.go
I noticed that the `UpdatePathAggregator4ByteAs()` function is returning an error related to malformed attribute list error:
```
Reason="notification-sent code 3(update) subcode 1(malformed attribute list)" State=BGP_FSM_ESTABLISHED Topic=Peer
```
A path that triggered this looked something like:
```
&{0 [] 138 [{MpReach(ipv6-unicast): {Nexthop: 2001:de8:1:2::33, NLRIs: [2404:b5c0::/32]}} {Origin: i} 134911 {Med: 98} {LocalPref: 55} {Aggregate: {AS: 134911, Address: 10.0.0.1}} {Extcomms: [2:2]} {As4Aggregator: {AS: 134911, Address: 10.0.0.1}} {LargeCommunity: [ 65102:1:1]}] []
```
We can see in the above the `Aggregate.AS` was `134911` which falls into 32-bit space, but we were only setting the aggregator in cases where the kind was a uint16 here: …
=> Fix UpdatePathAggregator4ByteAs() ignores 32bit value

cmd/gobgp/mrt.go
This PR fixes a comparison that was not being triggered when a RIB had a not valid peerIndex, causing the client to panic:
`panic: runtime error: index out of range [1] with length 1`
The same malformed MRT file would throw the following error with BGPDump as a comparison:
`Assertion failed: (e->peer_index < entry->dump->table_dump_v2_peer_index_table->peer_count), function process_mrtd_table_dump_v2_ipv6_unicast, file bgpdump_lib.c, line 687`
With this patch gobgp now shows the following error before exiting (as expected):
`invalid peer index: 1 (PEER_INDEX_TABLE has only 1 peers)`
Another test, when the peer index table is present, but contains 0 peers, still works as intended:
`invalid peer index: 0 (PEER_INDEX_TABLE has only 0 peers)`
=> Fix panic on malformed MRT injection

internal/pkg/table/table.go, internal/pkg/table/table_test.go, pkg/packet/bgp/bgp.go, pkg/packet/bgp/bgp_test.go
When ListPathRequest is done by a gRPC client including a malformed prefix,
the server would crash with an invalid memory address reference.
This commit fixes the crash by checking whether the parseCIDR method returned an error.
=> Fix crash on ListPathRequest with malformed prefix

BUILD.md, internal/pkg/zebra/zapi_test.go, pkg/packet/bgp/bgp_test.go, pkg/packet/bgp/validate_test.go, pkg/packet/bmp/bmp_test.go, pkg/packet/mrt/mrt_test.go, pkg/packet/rtr/rtr_test.go
Adding  [go-fuzz](https://go.dev/security/fuzz)  fuzz testing support.
=> [Fuzzing] fuzzing support for oss-fuzz

pkg/packet/bgp/bgp.go
I recently started using gobgp package libraries to parse BMP messages from a third party source (BIRD). BIRD has a bug whereby the BMP messages it emits do not have the transitive flag set on well known path attributes on route monitoring messages. GoBGP correctly checks for this condition [here](https://github.com/osrg/gobgp/blob/1b975be057fc02848d205361bdc5426110b99930/pkg/packet/bgp/validate.go#L230-L236). There is a subtle bug that shows up when parsing a BGP update message that fails this check which is that `PathAttribute.DecodeFromBytes()` exits early before it sets the `PathAttribute.Length`. 
Highlighting this with an example this is a byte slice from an update pack after gobgp has stripped out everything from the packet byte slice leaving Path Attributes and NLRI:
Byte slice …
=> fix: call validatePathAttributeFlags after parsing and setting path attribute length

pkg/server/server.go, pkg/server/sockopt_linux.go, test/scenario_test/bgp_router_test.py
Adds usage of the "prefix-based" TCP MD5 for dynamic neighbors. Non-dynamic neighbors will continue to use non-prefix based, which makes it more compatible with running on older kernels, as only 4.14+ includes the necessary support.
This change also includes tests of dynamic peers in general.
In the tests I tried to follow some of the naming/addressing that was in place already but might not have stuck with that as well as I could have.
Intended as fix for Issue #2589
=> Implementation of Dynamic Neighbor MD5 (Issue #2589)

pkg/server/server.go, pkg/server/server_test.go
It could be that a peer gets deleted and added back while it was transitionning from active to open confirm. In that case, the TCP connection from the old version of the peer could still be up. This is a problem if the server is a listener only as the remote peer would consider the old TCP connection as being valid and it won't be able to connect until the TCP connection is eventually cleaned by the Golang GC.
=> Make sure the TCP connection is closed when a peer is deleted

internal/pkg/table/table.go, internal/pkg/table/table_manager.go
This patch adds a special case in the destination hashmap for EVPN Type-2 routes, to index them by MAC address. This allows for direct access to the destination struct, instead of iterating over all destination and all paths. Such an access is performed for every EVPN Type-2 route received for EVPN MAC mobility handling.
In effect, this replaces an iteration over all known paths by a quick lookup to the MAC, leaving only an iteration to multiple paths to the same MAC (e.g. multihoming or through multiple VNIs).
The practical effect is a reasonable convergence time for large EVPN instances.
- before: 6m 7s
- after: 11s
The comparison was performed on a Xeon Silver 4209T, and an EVPN instance comprising of 13k EVPN type-2 routes. The time is measured by comparing the timestamp of the first …
=> evpn: fix quadratic evpn mac-mobility handling

pkg/server/grpc_server.go
Additionally change the `Key` to be the listener address, which is hopefully more useful than a difficult-to-decipher dump of the listener struct.
The previous behavior would result in log lines like the following, even if nothing went wrong:
```
time="2024-01-31T17:30:25Z" level=warning msg="accept failed" Error="<nil>" Key="&{0x140002e4000 {<nil> 0 0}}" Topic=grpc
```
With this change, the message is only logged if there was an error, and it will look like this:
```
time="2024-01-31T17:40:25Z" level=warning msg="accept failed" Error="lolol just testing" Key="127.0.0.1:59289" Topic=grpc
```
=> server: only log warning if grpcServer.Serve() returned an error.

pkg/server/server.go
Fixes a deadlock condition that can happen if StopBgp is called when the pending connection queue is full. During teardown, StopBgp calls a mgmtOp on the server goroutine which attempts to stop the goroutine accepting inbound connections, and waits for it to finish before continuing.
This connection goroutine can block if the connection queue is full, which is read by the same goroutine that processes all mgmtOps. This means that if the queue is full and the goroutine is currently blocked, then calling StopBgp will lead to a complete deadlock, as the connection goroutine will never close as it is trying to send to the queue, but the queue will not be read as the server goroutine is currently waiting for the connection goroutine to exit.
To correct this, a context has been added that gets …
=> server: Fix deadlock if StopBgp is called when conn queue is full

internal/pkg/table/destination.go, pkg/server/fsm.go, pkg/server/peer.go, pkg/server/server.go
Moves a number of heavily called debug lines behind if checks to avoid needless allocations of Fields objects and stringification of fields. For cases where the server is not set to "debug" log level, these fields were allocated on the heap and then immediately discarded - as well a number of these were stringifying state / NLRIs regardless of log level.
In servers with significant amounts of routes and BGP peers, this lead to a large amount of wasted allocations - in our case looking at Go's memory profiler, 25% of all allocations were from these lines alone.
=> logs: Guard frequently called logs behind if check

internal/pkg/table/message.go
- Changes table.(*packerV4).pack.func1 (split) to adjust the max parameter before using it to allocate slice size.  Previously the full max size was allocated then max was (possibly) truncated before further use.
=> Adjust size of packing slice before allocating

pkg/server/server.go, pkg/server/server_test.go
Currently, even though `ApplyPolicy` is called for determining the accepted routes after apply policy, the new route with attribute modifications is not returned. This is problematic for gRPC API users.
Validation is added within `TestListPathEnableFiltered` for all four cases that were described in https://github.com/osrg/gobgp/issues/2765. This PR makes the behaviour conform to "Case/Attempt 2" described in the issue.
=> Fix `ListPath` for `ADJ_IN` and `EnableFiltered=true` and add tests.

pkg/server/server.go, test/scenario_test/graceful_restart_test.py
Before this PR, when graceful restart was configured for a neighbor and when the restart flag was set by the restarting speaker, if the neighbor was not advertising the GR capability, the initial paths list was never sent by the restarting speaker to its neighbor
This is a problem when the server is configured with graceful restart for all its peers without knowing if the peer supports it. If some of the peers don't support it, they may never receive the routes from the restarting speaker, leading to an inconsistent routing state.
@fujita, I closed previous PR #2794 and re-created this new one with some modification based on the discussion there
=> graceful restart: send initial paths list to all neighbors

internal/pkg/table/path.go, internal/pkg/table/table.go, internal/pkg/table/table_manager.go, pkg/server/server.go, test/scenario_test/evpn_test.py
The mac mobility code used lookup tables to find the routes to the MAC address. It only considered the MAC itself, and not the associated MAC-VRF. This led to the complexity still being way too high when one MAC is present in all MAC-VRFs, like a virtual router or an anycast gateway.
This patch now considers the MAC-VRF for a route by looking up its route targets, and considers them all if multiple are present. This way, the lookup for routes that will participate in mac-mobility will be limited to the MAC-VRF. This allows to not blow up the CPU when a MAC address is present in a lot of MAC-VRFs.
The biggest behavioral change is now how mac-mobility is sharded. For example, it can now have the same MAC in multiple MAC-VRFs on different PEs. This is quite useful in highly multi-tenant …
=> evpn: scope mac-mobility handling to MAC-VRF of the route 

.github/workflows/ci.yml, .github/workflows/release.yml
Previously, we were using `go-version-file: 'go.mod'`, which refers to the `go: 1.20` directive in `go.mod`. That means that `go1.20.14` was being used as the toolchain version. That's very out-of-date and no longer maintained. We have run into sporadic runtime fatal errors, and I believe that using a newer Go version will help with this.
I could specify `'1.22'` instead, if that's preferred. I chose `stable` just because when future major Go versions are released, they will be picked up automatically on the next build-and-release GitHub Actions run.
The version used to build a specific `gobgpd` binary can be found with `go version -m ./gobgpd`.
=> ci: build with latest stable Go version

cmd/gobgp/neighbor.go, pkg/server/server.go, test/scenario_test/addpath_test.py
when a path that was previously filtered becomes advertised because another path is withdrawn, the sendMaxFiltered flag needs to be unset. Otherwise, this path would never be deleted from the peer unless the peer is removed.
=> send-max: fix flag when path is not filtered anymore

pkg/server/server.go
Fixes regression introduced by 832b2d99c7de2a5461e3028ed56aec1c8b59ad14 which breaks peerings with unspecified IPv6 local transport address.
Fixes: https://github.com/osrg/gobgp/issues/2844
=> Re-allow unspecified IPv6 local transport address

README.md, cmd/gobgpd/main.go, docs/sources/sentry.md, go.mod, go.sum
We would like to use Sentry with `gobgpd` to capture unexpected crashes
We've seen occasionally `gobgpd` crashed with corrupted memory and leaving basically no trace to investigate
With Sentry integration, we hope to there is a chance to capture more information from the crash
=> feature: add sentry integration to gobgpd

cmd/gobgpd/main.go, go.mod, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/server/rpki.go, pkg/server/server.go
As the issue #2854 demonstrates, Main FSM loop performance is crucial for overall GoBGP performance. While we're far from hitting those limits yet, we want to be sure that we have enough capacity in FSM loop.
To achieve that, we add FSM loop timing histograms, which are showing:
- timing_sec - amount of time handling each message took
- wait_sec - amount of time each message spent in a channel before it was received by the main FSM loop. The latter (wait times) allows to detect situation when FSM loop performance is inadequate, while the former (timings) allows to understand which component causes such delays.
For the sake of simplicity, further classification of message types, such as RouterID of the peer or name of gRPC operation is not made.
=> Add FSM loop timings

pkg/config/oc/bgp_configs.go, tools/pyang_plugins/gobgp.yang
Update gobgp.yang for AllowAsPathLoopLocal config option and generate bgp_configs.go.
Seems that the commit 16ea4f9c592a ("Add neighbor config option to bypass as-path loop detection on local (static) routes") updates bgp_configs.go by hand.
=> Update gobgp.yang for AllowAsPathLoopLocal config option

cmd/gobgp/global.go, pkg/apiutil/attribute.go, pkg/packet/bgp/bgp.go, pkg/packet/bgp/bgp_test.go, pkg/server/server.go
* add support for cli add/del operations
* add support for default route target via api/cli
* fix panic while deduplication of default route target
* fix rt membership validation, partial prefixes are still not supported, just 0/32/96-bit for consistency
* add tests
=> rtc: implement default route target and cli support

pkg/packet/bgp/bgp.go
1. On 64-bit platform, it takes less space to store an uint32 because an int is equivalent to int64. An uint32 is enough as AFI is 16-bit and SAFI is 8-bit.
2. On 32-bit platform, int is int32 and it is not big enough to encode all route families, notably the ones with AFI > 2**15. At runtime, this is not a problem, however, at compile time, we get an error.
=> bgp: turn RouteFamily into uint32

pkg/packet/bgp/bgp.go
=> packet: bgp: Fix LsAddrPrefix decoder

cmd/gobgp/common.go, cmd/gobgp/root.go
Fix the following warnings:
SA1019: grpc.DialContext is deprecated: use NewClient instead. Will be supported throughout 1.x. (staticcheck)
SA1019: grpc.WithBlock is deprecated: this DialOption is not supported by NewClient. Will be supported throughout 1.x. (staticcheck)
=> Fix staticcheck warnings

pkg/server/fsm.go, pkg/server/server.go
The default value for tcpkeepalive in the standard net package is 15 seconds, while the default value for BGP keepalive is 30 seconds. If the network is not good, the TCP connection is disconnected before BGP can send keepalive messages.
Therefore, BGP keepalive is effectively invalid.
The solution is that since we have BGP keepalive, we don't need to open tcp keepalive.
=> server: disable tcpkeepalive

api/capability.pb.go, pkg/apiutil/capability_test.go, proto/api/capability.proto
Use _UNSPECIFIED prefix for Enum zero value name.
Fix buf lint warnings.
=> api: Fix AddPath Cap Enum

api/gobgp.pb.go, cmd/gobgp/monitor.go, cmd/gobgp/neighbor.go, cmd/gobgp/policy.go, docs/sources/bgp-ls.md, docs/sources/lib.md, internal/pkg/table/policy.go, pkg/config/oc/util.go, pkg/metrics/metrics_test.go, pkg/server/grpc_server.go, pkg/server/server.go, pkg/server/server_test.go, proto/api/gobgp.proto
Use _UNSPECIFIED prefix for Enum zero value name:
PeerEvent::Type
ListPathRequest::SortType
RouteAction
PolicyDirection
Fix buf lint warnings.
=> api: Fix Enum prefix

pkg/server/server.go, pkg/server/server_test.go
This is useful when a BGP server needs to react to the remote capabilities received in the Open message from one of its peers.
=> peer: add remote capabilities to peer watch response

internal/pkg/table/destination.go, internal/pkg/table/path.go, pkg/server/server.go, pkg/server/server_test.go
1. Fix covert withdraw of an updated rtc path and it's responses.
2. Add tests for this problem and for the reason why deleted string had been added.
We have an interactive control plane for gobgp, that can send same rtc path to it. Same but not equal (with new comm for example). And in this case we see, that new rtc path is set in GRT, but responses for it are withdrawn.
[Appended a comment related to this pr as the commit message by Tomo]
=> fix covert withdraw of an updated rtc path

internal/pkg/table/destination.go, internal/pkg/table/path.go, pkg/server/server.go, pkg/server/server_test.go
more correct naming
more adequate tests
=> several small clarifications in 4ca2099fee19d043704ff04ddfe38f9294ca86be

test/scenario_test/long_lived_graceful_restart_test.py
This small maintenance PR is migrates from `unittest.assertEquals` to `unittest.assertEqual` which is deprecated from Python2.7:
```python
DeprecationWarning: Please use assertEqual instead.
```
It also fixes a few typos along the way.
=> fix: migrate to modern testing interface

api/extcom.pb.go, cmd/gobgp/global.go, pkg/apiutil/attribute.go, pkg/apiutil/attribute_test.go, pkg/packet/bgp/bgp.go, proto/api/extcom.proto, tools/spell-check/dictionary.txt
Currently GoBGPd unable to process EVPN routes with one or both of these extended communities present. 
This patch provides basic support for both of extcomms and so will enable gobgpd to process evpn routes with two new extcomm sub-types:
- 0x05 E-Tree Extended Community (https://datatracker.ietf.org/doc/rfc8317)
- 0x09 Multicast Flags Extended Community (https://datatracker.ietf.org/doc/rfc9251)
=> ADD: E-Tree and Multicast Flags EVPN extended communities support

.github/workflows/ci.yml
Add the `-v` flag to all `go test` invocations in the GitHub Actions CI workflow (`ci.yml`). This provides verbose output during test execution, which helps with debugging and tracking progress.
=> ci: enable verbose output for Go tests in CI workflow

.github/workflows/ci.yml
Add the `-v` flag to unit386.
The commit fe53aad5 ("ci: enable verbose output for Go tests in CI workflow") were supposed to add this.
=> ci: enable verbose output for unit386

test/lib/base.py
the invoke library is only used to run somme commands. it prompts a lot of useless debugging logs when a test fails.
=> chore: remove invoke run for testing

docs/sources/bgp-ls.md, docs/sources/lib.md, pkg/apiutil/util.go, pkg/metrics/metrics_test.go, pkg/server/bmp.go, pkg/server/grpc_server.go, pkg/server/grpc_server_test.go, pkg/server/mrt.go, pkg/server/server.go, pkg/server/server_test.go, pkg/server/zclient.go, test/scenario_test/bgp_router_test.py
```
WatchEvent(ctx, api.request, WatchEventMessageCallbacks{
OnPathUpdate func([]*apiutil.Path, time.Time)
OnBestPath   func([]*apiutil.Path, time.Time)
OnPathEor    func([]*apiutil.Path, time.Time)
OnPeerUpdate func(*apiutil.WatchEventMessage_PeerEvent, time.Time)
})
```
This will expose the simple and light `apiutil.Path` aim to
get access events without a big overhead, just a translation
from internal table.Path to flat apiutil.Path type.Introducing a new API call, that would give us access to the Events without exposing the watch() method.
Overall, this will give us access to fast BGP info, by removing the protobuf serialization (and object size) overhead.
Please note that GRPC similar API name, relay on bgpServer.API
=> api: introduce new WatchEvent path(s) library mode API call

internal/pkg/table/destination.go, internal/pkg/table/destination_test.go, internal/pkg/table/message.go, internal/pkg/table/path.go, internal/pkg/table/path_test.go, internal/pkg/table/table_manager.go, pkg/server/grpc_server.go, pkg/server/server.go
Improve performance by 10% ish by caching path attributes via a path attributes hash if needed
```
Before
BenchmarkMultiPath/Benchmark_Calculate-12                 598702              1837 ns/op             376 B/op         14 allocs/op
BenchmarkMultiPath/Benchmark_GetMultiBestPath-12         3420961               343.5 ns/op             0 B/op          0 allocs/op
After
BenchmarkMultiPath/Benchmark_Calculate-12         	  637652	      1764 ns/op	     376 B/op	      14 allocs/op
BenchmarkMultiPath/Benchmark_GetMultiBestPath-12  	 4771671	       298.0 ns/op	       0 B/op	       0 allocs/op
=> Improve dest.Calculate() and dest.GetMultiBestPath() performance

internal/pkg/table/message_test.go, internal/pkg/table/path.go, internal/pkg/table/policy.go, internal/pkg/table/policy_test.go, internal/pkg/table/table.go, pkg/apiutil/attribute.go, pkg/packet/bgp/bgp.go, pkg/server/server_test.go, pkg/server/zclient.go
Replace uses of net.IP with netip.Prefix for IPAddrPrefix and IPv6AddrPrefix.
When GoBGP was started, the net/netip package did not exist and net.IP was the standard type for representing IP addresses. However, with the introduction of netip.Addr in Go 1.18, we now have a more efficient and type-safe alternative.
Although netip.Addr may use slightly more memory for IPv4 addresses (as it always reserves space for IPv6), it eliminates the need for memory allocation on the heap, which is expected to improve performance, especially in high-throughput paths.
This patch replaces uses of net.IP with netip.Prefix type implemented by using netip.Addr for IPAddrPrefix and IPv6AddrPrefix.
We should use netip for IpAddrPrefixDefault however it means that this patch becomes much larger since we also …
=> pkg/packet/bgp: use netip for IPAddrPrefix and IPv6AddrPrefix

pkg/packet/bgp/bgp.go
Replace net.IP with netip.Addr for RouteDistinguisherIPAddressAS.
=> pkg/packet/bgp: use netip for RouteDistinguisherIPAddressAS

cmd/gobgp/global.go, pkg/apiutil/attribute.go, pkg/packet/bgp/bgp.go
Replace net.IP with netip.Addr for Ls structures.
=> pkg/packet/bgp: use netip for Ls structures

cmd/gobgp/global.go, cmd/gobgp/neighbor.go, pkg/packet/bgp/bgp.go, pkg/packet/bgp/bgp_test.go
Replace net.IP with netip.Addr for EVPNMacIPAdvertisementRoute, etc.
=> pkg/packet/bgp: use netip for EVPN related structures

internal/pkg/table/table.go, pkg/packet/bgp/bgp.go, pkg/packet/bgp/bgp_test.go
Replace net.IP with netip.Addr for ParseVPNPrefix.
=> pkg/packet/bgp: use netip for ParseVPNPrefix

pkg/apiutil/attribute.go, pkg/packet/bgp/bgp.go, pkg/packet/bgp/bgp_test.go
Replace net.IP with netip.Addr for LsPrefixDescriptor.
=> pkg/packet/bgp: use netip for LsPrefixDescriptor

pkg/server/server.go
Watcher Generate API with watchEventTypePreUpdate argument isn't used so we can remove it.
=> server: remove Watcher Generate API with watchEventTypePreUpdate

pkg/server/fsm.go, pkg/server/peer.go, pkg/server/server.go, pkg/server/server_test.go, test/scenario_test/rtc_test.py
1. Add a test for correct message sequencing: VPN paths must precede VPN EoR.  
While in the rtc deferral-time == 0 case, the VPN EoR is sent immediately after peering (because the RT list is empty), it is important to verify that with rtc deferral-time > 0, the VPN EoR is sent after all VPN routes. This test case checks for the correct order of route advertisement versus End-of-RIB signaling.
2. Fix double-sending of paths with rtc deferral-time > 0.  
The test also tracks the number of received messages and has revealed that each VPN route is sent twice: once as a reply to an RT, and then again in the full set of VPN paths after RTC EoR is received.  
To address this duplication, new VPN paths should not be sent in response to RTs during the initial state. In this model, GoBGP waits for …
=> don't answer for rt's while waiting for rtc eor

internal/pkg/table/table.go, internal/pkg/table/table_test.go
Remove bgp.NewPrefixFromFamily() usage because NewPrefixFromFamily() is useful only for families that use a prefix. Thus for such families, NewPrefixFromFamily() is called with empty prefix string to create an uninitialized object. That's error-prone.
This is preparation for removing bgp.NewPrefixFromFamily() completely.
=> table: remove bgp.NewPrefixFromFamily usage

pkg/apiutil/attribute.go, pkg/packet/bgp/bgp.go
Replace AddrPrefixInterface in flowSpecPrefix and flowSpecPrefix6 with IPAddrPrefix and IPv6AddrPrefix.
flowSpecPrefix uses AddrPrefixInterface as IPAddrPrefix so it's simpler to use IPAddrPrefix directly.
=> packet/bgp: use IPAddrPrefix for flowSpecPrefix

pkg/packet/bgp/bgp.go
Needs to pass options about Prefix SID attribute.
=> packet/bgp: fix decoding labels in SR

api/gobgp.pb.go, pkg/apiutil/util.go, pkg/server/fsm.go, pkg/server/server.go, proto/api/gobgp.proto
This PR adds comprehensive BGP peer disconnect reason reporting to improve monitoring and troubleshooting capabilities.
- **API Enhancement**: Added `DisconnectReason` enum to `PeerState` with 14 different disconnect reasons
- **New Fields**: Added `disconnect_reason` and `disconnect_message` fields to `PeerState`
- **FSM Enhancement**: Added `fsmBadPeerAS` constant and detection logic for bad peer AS scenarios
- **Conversion Logic**: Added `convertFSMStateReasonToAPI()` function to map FSM reasons to API enums
- **Event Updates**: Updated `WatchEvent` to include disconnect reason and message in peer events
- **API Utility**: Updated `apiutil.PeerState` to include new disconnect reason fields
- `DISCONNECT_REASON_ADMIN_DOWN` - Administrative shutdown
- …
=> feat: Add BGP peer disconnect reason reporting

api/attribute.pb.go, cmd/gobgp/global.go, docs/sources/bgp-ls.md, pkg/apiutil/attribute.go, pkg/packet/bgp/bgp.go, pkg/packet/bgp/bgp_test.go, proto/api/attribute.proto, tools/spell-check/ignore.txt
This adds the following implementation
- Target: SRv6 Endpoint Behavior TLV, SRv6 SID Structure TLV, SRv6 End.X TLV, SRv6 BGP PeerNode SID TLV
- Implement protobuf definitions and conversion
- Implement TLVs
- Implement CLI BGP-LS Node, Link, SRv6, and PrefixV6 NLRI parsing
gobgp command (Node NLRI):
```
gobgp global rib add -a ls node bgp protocol 2 identifier 7 local-asn 65001 local-bgp-ls-id 0 local-igp-router-id 0000.0000.0001 node-name r1 isis-area-id 490001 sr-algorithm 0 1
```
gobgp command (Link NLRI):
```
gobgp global rib add -a ls link bgp protocol 2 identifier 7 local-asn 65001 local-bgp-ls-id 0 local-igp-router-id 0000.0000.0001 remote-asn 65002 remote-bgp-ls-id 0 remote-igp-router-id 0000.0000.0002 link-local-id 1 link-remote-id 2 srv6-endpoint-behavior 57 srv6-sids …
```
=> Implement BGP-LS processing for RFC 9514

pkg/server/server.go
Use io.Discard if a logger isn't passed to NewBgpServer().
=> server: don't log anything if logger isn't specified

pkg/server/fsm.go, pkg/server/fsm_test.go, pkg/server/peer.go, pkg/server/server.go, pkg/server/server_test.go
Since the FSM state is read very frequently, using the FSM mutex isn't efficient. Use a lock-free structure.
=> server: make the FSM state lock-free

pkg/server/fsm.go, pkg/server/peer.go, pkg/server/server.go, pkg/server/server_test.go
Since `rfmap` is accessed for every received message, use `atomic.Value` to avoid locking. Also rfMap name, "RouteFamily", is odd so use familyMap.
=> server: use atomic.Value for fsm.rfMap
