osrg/gobgp

config/default.go

changed the key string to the map 'attributes'.

config: fix attribute name

---

bgpd.go
config/serve.go
policy/policy.go
policy/policy_test.go
server/peer.go
server/server.go
table/destination.go
table/destination_test.go
table/message.go
table/path.go
table/path_test.go
table/table.go
table/table_manager.go
table/table_test.go
tools/config/example_toml.go

policy: add prefix filter

---

table/path.go

Paths whose route family are other than ipv4 have nexthop information in
a mp_reach_nlri path attribute instead of a nexthop path attribute.

table: fix nexthop path attribute updating for normal BGP

---

policy/policy.go
server/peer.go
test/scenario_test/docker_control.py
test/scenario_test/quagga-rsconfig.go
test/scenario_test/quagga_access.py
test/scenario_test/route_server_policy_test.py
test/scenario_test/scenario_test_util.py

added scenario tests for policy and this patch has only IPv4 test cases.

Scenario test policy

---

cli/gobgpcli
server/peer.go

api: simplify adj-in/out json format

---

gobgp/main.go
tools/completion/gobgp-completion.bash

Reimplemented in golang. Easy to install rather than playing with
python package dependency.

add new cli 'gobgp'

---

server/peer.go

somehow the bad code was merged.

server: go fmt fix

---

server/server.go

server: show peers in the sorted order

---

api/rest.go
server/peer.go
server/peer_test.go
server/server.go

add:    curl -X POST   -d prefix=10.0.0.0/24 http://localhost:8080/v1/bgp/global/ipv4
delete: curl -X DELETE -d prefix=10.0.0.0/24 http://localhost:8080/v1/bgp/global/ipv4

api/server: add apis to add/delete routes to/from global rib

---

gobgp/main.go

cli: update help messages about the old cli name

---

gobgp/main.go

Added '-t' (--transport) option, which can take "ipv4" or "ipv6":
fujita@ubuntu:~/git/gobgp/gobgp$ gobgp neighbor
Peer           AS  Up/Down State       |#Advertised Received Accepted
10.0.255.1  65001 01:59:53 Establ      |          1        2        2
10.0.255.2  65002 01:59:53 Establ      |          2        1        1
2001:db8::7 65007    never Active      |          0        0        0
fujita@ubuntu:~/git/gobgp/gobgp$ gobgp neighbor -t ipv4
Peer          AS  Up/Down State       |#Advertised Received Accepted
10.0.255.1 65001 02:02:20 Establ      |          1        2        2
10.0.255.2 65002 02:02:20 Establ      |          2        1        1

cli: support specifying a transport for neighbor command

---

server/fsm.go

FSMHandler's holdTimer could be accessed by rx goroutine before it's
initialized. Let's use channel rather than sharing time.Timer pointer.

server: fix FSMHandler's holdTimer race

---

table/table_manager.go
table/table_manager_test.go

This reverts commit f8832eb4811f57d16211fe31986b395ffb3c6ff0.

Revert "table: withdraw an old best path when best path changed"

---

server/fsm.go
server/server.go

server: add logging about peer up/down

---

server/peer.go
table/path.go

server: don't path information if path include the same AS number

---

tools/completion/zsh/_gobgp

tools: add zsh completion for gobgp cli

---

config/bgp_configs.go
policy/policy.go
policy/policy_test.go
server/server.go
table/path.go
tools/pyang_plugins/bgpyang2golang.py

added ASPath and Community condition and Community action.

Policy aspath community

---

policy/policy.go
policy/policy_test.go
server/peer.go
test/scenario_test/constant.py
test/scenario_test/docker_control.py
test/scenario_test/gobgp_test.py
test/scenario_test/quagga-rsconfig.go
test/scenario_test/quagga_access.py
test/scenario_test/route_server_policy_test.py

added scenario test cases for following conditions and action:
- AS_PATH length condition
- AS_PATH list condition
- comminiity condition
- community action

scenario_test: add policy test cases for new action and conditions

---

test/scenario_test/docker_control.py

use exabgp inside the container.
I changed the way to remove existing docker containers to use 'docker stop' and 'docker rm'.

scenario_test: remove code to get the latest exabgp

---

server/peer.go
server/server.go

This could lead to a deadlock.

server: server goroutin can't access to outstanding directly

---

test/scenario_test/docker_control.py
test/scenario_test/route_server_malformed_test.py

improved malformed_test's execution time.

Fix malformed

---

.gitignore
api/gobgp.pb.go
api/gobgp.proto
gobgp/global.go
gomrt/main.go
gomrt/packet/mrt.go
gomrt/packet/mrt_test.go
packet/bgp.go
packet/bgp_test.go
packet/validate.go
packet/validate_test.go
server/grpc_server.go

FYI http://codeout.hatenablog.com/entry/2015/05/17/020555

add mrt route injector

---

table/destination.go
table/path.go
table/table_manager.go

this PR can be merged after #155

compare path deeper

---

test/scenario_test/bgp_router_test.py
test/scenario_test/lib/gobgp.py

stop using gobgp monitor command

---

tools/pyang_plugins/README.rst

tools/pyang_plugins: update README.rst

---

api/gobgp.pb.go
api/gobgp.proto
docs/sources/cli-command-syntax.md
docs/sources/filter-detail.md
gobgp/common.go
gobgp/policy.go
policy/policy.go
server/server.go

added as-prepend action support to cli.
I also added its description to doc.

Aspath prepend cli

---

server/fsm.go
test/scenario_test/bgp_router_test.py

also added scenario test to check active connection properly works

server: fix bug of active connection

---

server/server.go

Currently, if a monitor request sender doesn't read from bgpd some
time, a message could be dropped. Instead, this makes bgpd keep
messages in memory until they are read.

server: make monitor rcp request reliable

---

test/scenario_test/bgp_router_test.py
test/scenario_test/ci-scripts/jenkins-build-script.sh
test/scenario_test/docker_control.py
test/scenario_test/ibgp_router_test.py
test/scenario_test/noseplugin.py
test/scenario_test/route_server_ipv4_v6_test.py
test/scenario_test/route_server_malformed_test.py
test/scenario_test/route_server_policy_test.py
test/scenario_test/route_server_test.py

test: build docker image once, use it for all tests

---

packet/rtr.go

Added the Resource Public Key Infrastructure (RPKI) to Router Protocol.

packet: add RPKI to Router Protocol

---

server/server.go

server: fix one-shot mrt dump

---

test/scenario_test/bgp_router_test.py

test: insert sleep to fix unstable test

---

server/server.go

route server config has changed.

server: fix commit mess up

---

config/serve.go

gobgpd crashes when failing to read a config file at startup but
should not crash when failing to reload the config file.

config: don't crash when failing to reload config file

---

gobgpd/main.go
server/server.go

server: support to send notification to all peers when shutdown

---

policy/policy.go

policy: kill unused code

---

config/bgp_configs.go
tools/pyang_plugins/README.rst
tools/pyang_plugins/bgpyang2golang.py
tools/pyang_plugins/gobgp.yang

added gobgp-specific elements by using yang's 'augment' statements.

Yang gobgp augment

---

README.md
docs/sources/flowspec.md

doc: add flowspec document

---

config/default.go

config: fix peer type detection

---

gobgp/neighbor.go
packet/bgp.go

Reported-by: KATO Junya <kato.junya@lab.ntt.co.jp>

packet/cli: don't put nexthop in flowspec mp_reach_nlri path attribute

---

api/gobgp.pb.go
api/gobgp.proto
gobgp/neighbor.go
server/peer.go
server/server.go

*: s/distribute/in

---

test/scenario_test/ci-scripts/jenkins-build-script.sh
test/scenario_test/run_all_tests.sh

test: add a script for local scenario testing

---

gobgp/monitor.go
gobgp/neighbor.go
server/server.go
table/destination.go

gobgp: improve the time to show routes

---

server/server.go

server: fix LOCAL_RIB sends back sorted ipv4 routes

---

policy/policy.go
table/path.go
test/scenario_test/gobgp_test.py
test/scenario_test/policy/policy_generator.go
test/scenario_test/quagga_access.py
test/scenario_test/route_server_policy_test.py

added test cases for extended community action.
I also fixed the problem on appending extended communities.

scenario_test: add ext-community action test

---

config/default.go
gobgpd/main.go
packet/rtr.go
server/rpki.go
server/server.go

config file support rpki configuration

---

.travis.yml

tests with go1.5

---

server/server.go
table/destination.go

server: fix for sorting adj-in/out routes

---

gobgp/neighbor.go
server/server.go
table/destination.go

speed up showing ipv6 routes

---

packet/validate.go
table/destination.go
table/table.go

*: better log msg

---

zebra/zapi.go
zebra/zapi_darwin.go
zebra/zapi_linux.go

Not tested on Mac OS X but at least buildable.

make gobpgd buildable on Mac OS X

---

test/scenario_test/ci-scripts/jenkins-build-script.sh
test/scenario_test/lib/base.py
test/scenario_test/lib/exabgp.py
test/scenario_test/run_all_tests.sh

test: unleashing test concurrency

---

docs/sources/grpc-client.md
tools/grpc/ruby/get_neighbors.rb

doc/tools: add doc explains how to interact with gobgp using ruby

---

gobgp/common.go

cli: catch up with google.golang.org/grpc update

---

api/gobgp.pb.go
api/gobgp.proto
docs/sources/rpki.md
gobgp/common.go
gobgp/mrt.go
gobgp/rpki.go
server/grpc_server.go
server/rpki.go
server/server.go

rpki: support show the state of RPKI servers

---

docs/sources/grpc-client.md

docs: fix wrong direction

---

gobgp/cmd/global.go

cli: support appending encapsulation extended community to evpn routes

---

api/gobgp.pb.go
api/gobgp.proto
gobgp/cmd/global.go
gobgp/cmd/mrt.go
server/server.go
table/destination.go
table/path.go
test/scenario_test/lib/base.py

api: enable injecting multiple routes at once

---

gobgp/cmd/global.go

cli: fix incomplete help msg

---

packet/bmp.go
packet/bmp_test.go

packet: add bmp serialize support

---

config/bgp_configs.go
docs/sources/zebra.md
gobgpd/main.go
server/server.go
test/scenario_test/lib/gobgp.py
tools/pyang_plugins/gobgp.yang
zebra/zapi.go

This patch includes new gobgp.yang that has zebra configuration and bgp_configs.go generated from new yang file.
It's also includes new server.go that gets zebra configuration from file and the document for the configuration.

Yang zebra

---

README.md
docs/sources/zebra.md

add link to zebra doc

---

test/scenario_test/bgp_zebra_test.py
test/scenario_test/lib/base.py
test/scenario_test/lib/quagga.py

container was wrong to check whether the reachable in the test.
thus, modified to check the reachability between the correct container
and implemented modifications of the logic associated with the above.

scenario_test: fix bug of bgp_zebra_test

---

docs/sources/grpc-client.md
tools/grpc/python/get_neighbor.py

Needs to change it because of renaming name from Grpc to GobgpApi.

tools: change for renaming api-name of package/service to gobgpapi

---

gobgp/cmd/policy.go
policy/policy.go
policy/policy_test.go

also shut up inappropriate warning message when no mask lenge is
given.

policy: refactor Prefix implementation

---

server/server.go

server: give change to handle accepted conn before handling paths

---

api/gobgp.pb.go

api: sync with the latest protoc-gen-go

---

policy/policy.go
policy/policy_test.go

policy: support removing community wich regexp

---

policy/policy.go

policy: fix removing community wich multiple regexp conditions

---

config/serve.go
gobgpd/main.go

add log messages at bootup

---

server/server.go

server: log admin operations

---

server/server.go

gobgpd should die after sending a notification all the peers in
the established state.

server: fix TERM signal handling

---

policy/policy.go
server/server.go
table/path.go
table/table_manager.go
test/scenario_test/route_server_policy_test.py

export neighbor condition must match to the remote address of
destination peer.

policy: fix bug of export neighbor condition matching

---

server/peer.go
server/server.go

server: need to send withdrawn for filtered routes after softreset

---

server/peer.go

server: fix the number of accepted routes

---

server/server.go

server: can safely clear staleAccepted after reset

---

gobgp/cmd/global.go
gobgp/cmd/neighbor.go
server/grpc_server.go
server/server.go

cli: add command to show global policy

---

docs/sources/cli-command-syntax.md
gobgp/cmd/vrf.go
server/server.go

cli: fix vrf add command

---

gobgp/cmd/neighbor.go

gobpg: add route statistics to neighbor <address> command output

---

server/server.go

policy: fix bug of not applying global export policy in getBestFromLocal

---

gobgpd/main.go

add net/http/pprof support

---

server/peer.go

server: logging received notificaiton

---

gobgp/cmd/common.go

gobgp: fix the default address family handling

---

server/server.go

server: need to apply IN policy for newly added peer

---

test/scenario_test/route_server_policy_test.py

Currently, it's not easy to add or delete a test because it's
necessary to specify a number for each test by hand. Instead, let's
assign a number for each test automatically.

scenario_test: refactor route_server_policy_test

---

server/peer.go
server/server.go

server: fix the number of accepted

---

gobgpd/main.go
server/server.go

server: properly handle invalid policy config

---

gobgpd/main.go
server/server.go

server: kill unnecessary code

---

table/policy.go
table/policy_test.go
tools/config/example_toml.go

I removed several warnings pertaining to policy.

Go vet fix

---

server/peer.go
test/scenario_test/lib/quagga.py
test/scenario_test/route_server_policy_grpc_test.py

server: fix ROUTE_REFRESH handling

---

server/rpki.go
server/rpki_test.go

A single prefix in ROA could have multiple ASes.

server: fix rpki to handle roa with multiple ASes

---

server/rpki.go
server/rpki_test.go
table/destination.go
table/destination_test.go

also clean up functions to create a radix key.

server: fix radix key bug in rpki test

---

server/rpki_test.go

Add some examples for RPKI Validation.

Add examples for rpki

---

api/gobgp.pb.go
api/gobgp.proto
gobgp/cmd/common.go
gobgp/cmd/monitor.go
gobgp/cmd/neighbor.go
server/grpc_server.go
server/peer.go
server/server.go

Signed-off-by: YujiOshima <yuji.oshima0x3fd@gmail.com>

api: confirm api.Peer to openconfig and add ModPeer api

---

README.md

add waffle.io badge

---

gobgp/cmd/vrf.go

gobgp: go fmt fix

---

server/peer.go

server: fix lacking capability fields

---

tools/grpc/python/get_neighbor.py

tool: update grpc python example code

---

server/peer.go

server: kill unncessary rfMap update

---

test/scenario_test/README.md
test/scenario_test/route_server_malformed_test.py
test/scenario_test/route_server_policy_grpc_test.py
test/scenario_test/route_server_policy_test.py
test/scenario_test/run_all_tests.sh

support the run test in sequential
- route_server_policy_test.py
- route_server_policy_grpc_test.py
- route_server_malformed_test.py

Scenario test

---

gobgp/cmd/neighbor.go
packet/bgp.go

packet: add String() to PathAttributeAsPath and PathAttributeAs4Path

---

gobgp/cmd/common.go
server/rpki.go
server/rpki_test.go
table/destination.go
table/destination_test.go

rpki: fix IPv4-mapped addresss handling

---

packet/bmp.go

bmp: use BMP_VERSION

---

packet/bgp.go

packet: fix extended community parsing

---

api/gobgp.pb.go
api/gobgp.proto
gobgp/cmd/rpki.go
server/grpc_server.go
server/server.go

rpki: grpc support

---

packet/bmp.go

Should be exported like other members.

bmp: export flags member in BMPPeerHeader

---

tools/completion/gobgp-completion.bash

Support to the completion of following commands.
- gobgp rpki enable
- gobgp mrt update enable
-                              disabel
-                              rotate
-                              reset

cli: update bash_complition

---

test/scenario_test/ci-scripts/jenkins-build-script.sh

test: fix jenkins script

---

table/destination.go
table/destination_test.go
table/path.go
table/table.go

this is a preparation for add-path recv/send feature

table: sort all known paths instead of just selecting best

---

server/server.go

With this fix, the RPC API works like the following:
$ gobgp global rib
Network             Next Hop             AS_PATH              Age        Attrs
*>  210.173.160.0/19    210.173.172.65       65001                00:00:41   [{Origin: i}]
$ gobgp global rib 210.173.176.1
Network             Next Hop             AS_PATH              Age        Attrs
*>  210.173.160.0/19    210.173.172.65       65001                00:01:17   [{Origin: i}]

server: fix show rib with host address

---

server/server.go
table/table_manager.go
table/table_manager_test.go
test/performance_test/main.go

table: remove useless table owner member

---

api/gobgp.pb.go
api/gobgp.proto
gobgp/cmd/rpki.go
server/rpki.go

rpki: show ROA with server information

---

server/server.go

server: don't import path including looped as path

---

server/server.go

server: fix IMPORT POLICY handling for newly added peers

---

api/gobgp.pb.go
api/gobgp.proto
gobgp/cmd/common.go
gobgp/cmd/monitor.go
gobgp/cmd/mrt.go
gobgp/cmd/neighbor.go
gobgp/cmd/rpki.go
packet/bgp.go
server/grpc_server.go
server/server.go
table/path.go

api: refactor afisafi api

---

server/server.go

This fixes softresetout to send withdrawn updates for only routes in
adj-out.
Currently, softreset sends withdrawn updates for ALL routes rejected
by export policy. The problem is, even if export policy is configured
to rejecte any routes, softreset sends withdrawn updates.

server: fix softresetout to send withdrawn for only routes in adj-out

---

table/message.go

table: always try to merge NLRIs to one message

---

api/gobgp.pb.go
api/gobgp.proto
gobgp/cmd/rpki.go
server/rpki.go
server/rpki_test.go
server/server.go

rpki: support multiple roa servers

---

gobgp/cmd/rpki.go
server/rpki.go
server/server.go

gobgp rpki server <ip address> reset|softreset|enable
reset: close a tcp conneciton and retry to connect and send ResetQuery
softreset: send ResetQuery
enable: send SerialQuery

rpki: support reset/softreset/enable operation

---

server/rpki.go

Sort the results in order of prefix, maxlen, as, and roa server.

rpki: sort ROA results

---

server/server.go

bmp: send post-policy routes when connected to bmpd

---

docs/sources/grpc-client.md
tools/grpc/ruby/get_neighbors.rb

updated installation instructions for ruby gRPC and the example script.

doc: update ruby grpc

---

api/gobgp.pb.go
api/gobgp.proto
config/bgp_configs.go
config/default.go
gobgpd/main.go
server/server.go
tools/pyang_plugins/gobgp.yang

if port < 0, gobgpd won't listen on tcp:179

*: add global listen port configuration

---

docs/sources/grpc-client.md
gobgp/cmd/root.go
gobgpd/main.go
server/grpc_server.go
tools/grpc/cpp/gobgp_api_client.cc
tools/grpc/nodejs/get_neighbors.js
tools/grpc/python/get_neighbor.py
tools/grpc/ruby/get_neighbors.rb

also add an option to change grpc port

gobgpd/gobgp: change grcp port to 50051 from 8080

---

server/rpki.go

rpki: handle withdraw

---

table/policy.go

Sprintf() to stringify Fields is heavy

policy: remove heavy debug msg

---

test/scenario_test/global_policy_test.py

test: add global policy test

---

server/rpki.go

rpki: fix serial notify handling

---

table/path.go

table: fix NewBitmap's size calculation

---

gobgp/cmd/rpki.go
server/server.go
table/destination.go

$ gobgp rpki validate
validates all the paths in the table with the current ROAs.

rpki: add rpki validate API

---

gobgp/cmd/monitor.go

gobgp: improve rpki monitor output

---

server/rpki.go

It needs to respond with ResertQuery when CacheReset was received.

server: fix cache reset handling

---

packet/bmp.go

bmp: fix peerheader ip handling

---

server/bmp.go

server: fix needless warnings about writing to dead bmp connection

---

server/bmp.go

bmp: try to reconnect after write failure

---

docs/sources/grpc-client.md

Signed-off-by: Hiroshi Yokoi <yokoi.hiroshi@po.ntts.co.jp>

doc: add java section

---

server/peer.go
table/adj.go
table/table_manager_test.go

fix adjrib regression due to the d2801681 commit.

table: fix adjrib regression

---

server/rpki.go

Seems that sometimes it fails to get the proper data from a socket.

rpki: use io instead of bufio

---

gobgp/cmd/bmp.go
gobgp/cmd/common.go
gobgp/cmd/global.go
gobgp/cmd/monitor.go
gobgp/cmd/mrt.go
gobgp/cmd/neighbor.go
gobgp/cmd/policy.go
gobgp/cmd/rpki.go
gobgp/cmd/vrf.go

cli: make error output json format when `-j` option is specified

---

server/fsm.go

fsm: remove MsgDst

---

table/path.go

table: sort Flowspec components

---

gobgp/cmd/global.go
table/path.go

cli: sort Flowspec components

---

docs/sources/flowspec.md
gobgp/cmd/global.go
packet/bgp.go

packet: multiple flow spec fragmentation flags

---

gobgp/cmd/global.go

cli: sort path attributes

---

gobgp/cmd/common.go
gobgp/cmd/global.go
table/path.go

cli: delete duplicated code

---

table/policy.go

https://github.com/osrg/gobgp/issues/754

policy: fix crash to remove statement from policy without statements

---

server/fsm.go
server/sockopt_linux.go

fsm: support active connection with md5 and binding

---

.travis.yml
test/lib/quagga.py
test/scenario_test/bgp_router_test.py
test/scenario_test/ci-scripts/travis-build-script.sh
test/scenario_test/ibgp_router_test.py
test/scenario_test/route_reflector_test.py
test/scenario_test/route_server_as2_test.py
test/scenario_test/route_server_ipv4_v6_test.py
test/scenario_test/route_server_test.py

This patch enables scenario test to be executed on TravisCI.

scenario_test: run scenario test on travis

---

table/path.go

we support this for iBGP. why not for eBGP.

table: support advertising local route with specified nexthop via eBGP

---

server/sockopt_nonlinux.go

server: fix compile error on non-linux platform

---

config/serve.go
gobgpd/main.go

the main goroutine doesn't need to do so.

server: move SIGHUP handling to config file reader goroutine

---

server/server.go

server: wait AcceptTCP() return when closing listeners

---

server/watcher.go

server: fasten mrt write

---

docs/sources/getting-started.md

Added 
wget https://raw.githubusercontent.com/osrg/gobgp/master/tools/completion/gobgp-static-completion.bash
and wget https://raw.githubusercontent.com/osrg/gobgp/master/tools/completion/gobgp-dynamic-completion.bash
Both files are required by gobgp-completion.bash

added wget for gobgp static and dynamic bash

---

README.md

More handly. Also remove unused waffle.io.

doc: replace gitter with Slack

---

.travis.yml

travis-ci: add slack integration

---

.travis.yml

travis-ci: add slack integration with encrypt

---

tools/grpc/cpp/gobgp_api_client.cc

Correction of errors during compilation of gRPC client for C++.

Errors while compile gRPC client for C++

---

docs/sources/flowspec.md
packet/bgp/bgp.go

docs/packet: s/draft-ietf-idr-flowspec-redirect-rt-bis-05/RFC7674

---

server/rpki.go

rpki: export ROAEvent for library usage

---

gobgp/cmd/mrt.go
packet/mrt/mrt.go
packet/mrt/mrt_test.go
server/server.go
server/watcher.go

move mrt stuff from bgp to mrt package.

packet: create mrt package

---

config/default.go
gobgp/cmd/bmp.go
gobmpd/main.go
packet/bgp/bgp.go
packet/bgp/bgp_test.go
packet/bgp/helper.go
packet/bmp/bmp.go
packet/bmp/bmp_test.go
packet/rtr/rtr.go
packet/rtr/rtr_test.go
server/bmp.go
server/rpki.go
server/server.go

move rtr stuff from bgp to rtr package.

packet: create rtr package

---

table/policy_test.go

policy: add unittest ParseCommunityRegexp()

---

docs/sources/lib.md

docs: update lib.md

---

gobgp/cmd/neighbor.go

gobgp: fix uptime in gobgp neighbor command

---

server/fsm.go
server/server.go

server: ignore stale fsm messages

---

config/serve.go

config: fix ReadConfigfileServe() not to loop endlessly

---

config/util.go
server/fsm.go
server/fsm_test.go
server/server.go

admin-down : 6/2
peer-as/neighbor-address : 6/3
other : 6/6

server: fix to send more appropriate notification code/subcode

---

server/fsm.go
server/server.go

server: don't modify admin-down config

---

server/fsm.go

server: log notification error code

---

packet/bgp/bgp.go
packet/bgp/bgp_test.go
server/fsm.go

server: pretty notification error code log

---

server/fsm.go

fix 3ced192e5c5bda81290e4a13d17bedd66b36b439
we've already sent one before arriving here

server: stop sending notification message twice

---

zebra/zapi.go

server: go fmt

---

table/destination.go
table/destination_test.go

table: fix Med comparison in best path selection

---

docs/sources/policy.md

docs: update policy.md

---

tools/completion/gobgp-completion.bash

tools: support loading completion scripts when bash boots up

---

server/sockopt_linux.go

server: fix socket leak in DialTCPTimeoutWithMD5Sig()

---

server/grpc_server.go

Serve() returns when accept() failed. After that, gobgp stop listening
on grpc port (no more grpc request).
This patch makes sure that gobgp starts listening on grpc port again.

server: handle grpc Serve() error

---

docs/sources/getting-started.md

docs: update go versions

---

docs/sources/cli-command-syntax.md

docs: fix typos in cli examples

---

table/adj.go

table: use path Equal method in adj rather than homegrown funciton

---

gobgp/cmd/common.go
table/message.go

The current code wrongly converts a single api.Path to multiple local
path strcutures if api.Path has MP_REACH with multiple NLRIs.

cli: fix converting api.Path

---

test/scenario_test/ci-scripts/travis-build-script.sh
test/scenario_test/route_server_test3.py

test ebb2c9727a4002ab1b90d43485caf9b30937f372

test: check (*Path).Equal() is working correctly

---

server/collector.go

Ping InfluxDB to verify the connection at collector initialization and
create the database.

collector: ping InfluxDB and create database at startup

---

server/bmp.go
server/collector.go
server/monitor.go
server/watcher.go
server/zclient.go

server: remove restart() from watcher interface

---

.travis.yml

travis: add 'go fmt' test

---

packet/bgp/bgp.go

As specified in RFC7510 / RFC Errata 4350

bgp: add tunnel type MPLS in UDP

---

server/fsm_test.go

somehow travis-ci didn't catch

server: fix unit test

---

api/gobgp.pb.go

api: catch up the latest grpc

---

server/fsm_test.go
server/mrt.go
server/server.go

server: delete unused functions and variables

---

server/fsm.go

fsm: do two-bytes AS translation if didn't sent 4byte cap

---

table/message.go

Fix the following commit:
commit de58be441150daf8943a5a66ced6703b8201303e
Author: FUJITA Tomonori <fujita.tomonori@lab.ntt.co.jp>
Date:   Sun Jun 26 23:18:23 2016 +0900
support AGGREGATOR and AS4_AGGREGATOR conversion

fix support AGGREGATOR and AS4_AGGREGATOR conversion

---

server/grpc_server.go
server/server.go

move gRPC-related code for REQ_RIB to grpc_server.go

---

gobgpd/main.go
server/grpc_server.go
server/server.go

move gRPC-related code for SoftReset to grpc_server.go

---

server/server.go

Fix the regression due to c4fe45902e736a858c4870bcab01c9143551f696
Also switch from Fatal from Warn.

server: fix wrong log message

---

server/server.go

server: UpdateNeighbor() needs address parameter checking

---

api/grpc_server.go
config/bgp_configs.go
docs/sources/mrt.md
gobgpd/main.go
server/mrt.go
server/server.go
tools/pyang_plugins/gobgp.yang

Only global rib dumping is supported for now.

support mrt table dump (TABLE_DUMPv2 format)

---

gobgp/cmd/global.go

cli: fix ParseExtendedCommunities() to correctly parse action 'accept'

---

config/bgp_configs.go
docs/sources/mrt.md
server/mrt.go
server/server.go
tools/pyang_plugins/gobgp.yang

mrt: support per-peer table dump with route server configuration

---

api/grpc_server.go

the feature was somehow dropped

api: support address family filtering of MonitorRib API

---

docs/sources/flowspec.md
gobgp/cmd/global.go
packet/bgp/bgp.go

$ gobgp global rib -a ipv4-flowspec add match protocol 100 then discard
close #1052

cli: support setting flowspec "procotol" in octet

---

.travis.yml

travis: add go1.7

---

server/mrt.go

Having two interval options easily confuse users. With this, either
can be specified.
If you specify the rotation interval, gobgpd dumps a table and rotates
a log file every the rotation interval.

mrt: fix rotation and dump interval handling in table mode

---

.travis.yml

travis: use global environment variable for DOCKER_IMAGE

---

packet/bgp/bgp.go

$ gobgp g ri -a ipv4-flowspec add match protocol '>tcp' then accept
$ gobgp g ri -a ipv4-flowspec add match protocol '>40&<50' then accept
$ gobgp g ri -a l2vpn-flowspec add rd 100:100 match ether-type '>ipv4' then accept
close #1084

bgp/cli: support flowspec ip-proto/ether-type range match

---

gobgp/cmd/common.go

cli: add description to PeerConf struct

---

tools/pyang_plugins/README.rst

Use the specific commit id.
[ci skip]

tools: use forked openconfig repository

---

packet/bgp/bgp.go
packet/bgp/bgp_test.go
server/server.go
table/destination_test.go
test/scenario_test/bgp_router_test.py

server: fix bug of withdrawal handling

---

packet/bgp/bgp.go

Add BLACKHOLE community support (RFC7999)

---

server/server.go

server: handle management requests quicker under heavy load

---

packet/bgp/bgp.go

https://www.ietf.org/rfcdiff?url2=draft-ietf-idr-large-community-05

New Early IANA Allocation

---

api/grpc_server.go

bmp: fix wrong monitoring policy type translation

---

client/client.go
server/rpki.go
server/rpki_test.go
server/server.go
table/roa.go

client: remove server package dependency

---

gobgpd/main.go

gobgpd: support global policy assignment update via configuration file

---

README.md

docs: add link to Shu Sugimoto's tutorial

---

server/rpki.go
server/rpki_test.go

I want to use server/rpki.go for library on my application.
Furthermore I've added a feature to return the matched RoaBucket when ValidatePath() is executed.
Because we can't see which ROA the result was validated with.

Want to use server/rpki.go for library usage

---

server/rpki.go

Needs to update the state before copying it.

server: fix rpki server state

---

server/server.go

server: avoid accessing to globalRib before its initialization

---

docs/sources/policy.md

add note that prefix-set has either v4 or v6.
[skip ci]

doc: update policy

---

.travis.yml

Too unstable on travis-ci. Just try cross-compile test.

travis: drop osx test

---

zebra/zapi_test.go

zebra: fix unittest on OSX

---

config/bgp_configs.go
tools/pyang_plugins/gobgp.yang

update the yang file for the commit 59ec403de73d4c83ef28291661941c6334480ebd.

config: update yang file

---

.travis.yml
test/lib/base.py
test/lib/gobgp.py
test/lib/quagga.py
test/scenario_test/bgp_zebra_nht_test.py

The following patches implement the simple test case for the Nexthop Tracking feature which provided with Quagga/Zebra integration.

scenario_test: Add test for Nexthop Tracking

---

table/table.go

This is a fix for the regression bug #1081

gobgp: Fix for gobgp global rib <ip>

---

README.md

doc: fix README formatting

---

api/grpc_server.go
test/scenario_test/bgp_unnumbered_test.py

fix NewNeighborFromAPIStruct() regression.

cli: show neighbor max prefix config

---

docs/sources/getting-started.md
docs/sources/graceful-restart.md
docs/sources/unnumbered-bgp.md
gobgp/cmd/neighbor.go

updated code base and documentation

Spelling error on Client neighbor command

---

docs/sources/getting-started.md

doc: update required go versions to 1.7 or later

---

server/fsm_test.go

Add sync.Mutex to guard access to MockConnection to prevent tests ran with -race from failing. In addition change the calls to the fmt package to use t.Log show they only show with the -v flag to prevent unwanted noise between test runs. It has the added benefit of providing a file and line number as well.

server/fsm_test.go: fix race condition during tests

---

test/scenario_test/graceful_restart_test.py

This patch adds tests for graceful restart with multiple peers (to cover bugs like #1296).

test: Test for Graceful Restart with multiple peers

---

packet/bgp/bgp.go
packet/bgp/helper.go

packet: fix addpath capability parser/serializer

---

docs/sources/grpc-client.md
tools/grpc/cpp/Makefile
tools/grpc/cpp/build.sh
tools/grpc/cpp/gobgp_api_client.cc
tools/grpc/java/src/gobgp/example/GobgpSampleClient.java
tools/grpc/python/get_neighbor.py
tools/grpc/ruby/get_neighbors.rb

This PR updates gRPC document and sample codes to work with the latest GoBGP, gRPC and ProtoBuf and so on.

Update gRPC document and sample codes

---

docs/sources/configuration.md
gobgp/cmd/neighbor.go

docs: update configuration.md

---

gobgp/cmd/neighbor.go

cli: fix aspath option format

---

client/client.go
table/destination.go

fix addpath send withdraw

---

docs/sources/cli-command-syntax.md
gobgp/cmd/global.go

also add an example to cli doc.

improve cli addpath usage message

---

server/sockopt_linux.go

https://github.com/osrg/gobgp/issues/1391

server: fix active connection error check

---

server/zclient.go

Seems that zebra could send a route message without nexthop (makes
sense for withdraw).

server: fix zclient to handle route messages without nexthop

---

server/sockopt.go
server/sockopt_darwin.go
server/sockopt_stub.go

server: add sockopt ttl support to darwin

---

README.md

README: add binary release link

---

README.md

README: update developing GoBGP for dep

---

config/default.go
docs/sources/ebgp-multihop.md
docs/sources/ttl-security.md

This PR adds the initial configuration guide for eBGP Multihop and TTL Security feature.

docs: Configuration guide for eBGP Multihop and TTL Security

---

README.md

docs: add required go versions to README

---

server/server.go

server: fix AddPath to return uuid properly

---

server/server.go
server/zclient.go

This PR enables zclient to register all nexthops contained in RIBs and also unregister nexthop if there is no path bound for that nexthop.

zclient: Register all nexthops and unregister uninterested nexthops

---

docs/sources/evpn.md

Along with changing the format of "gobgp global rib -a evpn" command, this PR updates the tutorial for EVPN.
This PR includes updates of output examples and some improvements of example commands and settings.

docs/sources/evpn: Update tutorials

---

api/grpc_server.go

This PR include improvement for the code inspection tools (e.g., gometalinter).

api/grpc server: Improve code inspection result

---

docs/sources/cli-command-syntax.md
docs/sources/flowspec.md
gobgp/cmd/global.go

This PR updates the help message of CLI and the syntax description on the document page.

cli/doc: Update CLI syntax help messages

---

server/bmp.go

Needs to set set A flag in Per-Peer Header if the peer use the legacy
2-byte AS_PATH format.

bmp: set A flag in Per-Peer Header

---

docs/sources/zebra-multipath.md

This patch adds a new document explains Equal Cost Multipath routes with
Zebra integration.

docs: Equal Cost Multipath Routing with Zebra

---

.travis.yml

travis: remove useless "go" section

---

zebra/zapi.go

Fixes https://github.com/osrg/gobgp/issues/1549

zebra/zapi: Fix Zebra API type when IPv6 routes

---

test/lib/base.py
test/lib/gobgp.py
test/lib/quagga.py
test/scenario_test/bgp_zebra_test.py

Fixes [the comment on #1552](https://github.com/osrg/gobgp/pull/1552#issuecomment-356133736)

scenario_test/bgp_zebra_test: Fix ping reachability tests

---

test/lib/bird.py
test/lib/gobgp.py
test/lib/quagga.py
test/lib/yabgp.py

Currently, scenario test library does not wait for the daemons boot in
containers at starting up or after sending SIGHUP for reloading new
configurations.
So some test cases (e.g., graceful_restart_test.py) fails occasionally
to insert static routes into GoBGP after reloading new configurations.
This patch fixes to wait for the daemons boot and improves the stability
of scenario tests.
Note: This patch does not introduce these improvements to
BagpipeContainer and ExaBGPContainer, because;
- Docker image for BaGPipe, which used in scenario test library, is too
old and BagpipeContainer does not seem to be used in the current test
cases.
- The version of ExaBGP in "osrg/exabgp" Docker image has no way to ask
the daemon status other than "ps" command ("ps" is already done, but
not enough). If …

test/lib/{bird,gobgp,quagga,yabgp}: Wait for daemon boot

---

.markdownlint.json
.travis.yml
README.md
docs/sources/add-paths.md
docs/sources/bmp.md
docs/sources/cli-command-syntax.md
docs/sources/cli-operations.md
docs/sources/configuration.md
docs/sources/dynamic-neighbor.md
docs/sources/ebgp-multihop.md
docs/sources/evpn.md
docs/sources/getting-started.md
docs/sources/graceful-restart.md
docs/sources/grpc-client.md
docs/sources/lib.md
docs/sources/mrt.md
docs/sources/peer-group.md
docs/sources/policy.md
docs/sources/route-reflector.md
docs/sources/route-server.md
docs/sources/rpki.md
docs/sources/ttl-security.md
docs/sources/unnumbered-bgp.md
test/scenario_test/README.md
tools/completion/README.md
tools/route-server/README.md
tools/spell-check/README.md

This PR improves the results of markdownlint and also adds a new UT to invoke markdownlint.
When using IDE (e.g. VSCode), we can easily check the results of markdownlint and it should not be a heavy burden to write docs.

*.md: Improvements for markdownlint

---

gobgp/cmd/neighbor.go
packet/bgp/bgp.go
packet/bgp/validate.go
server/fsm.go
server/rpki.go
table/destination.go
table/message.go
table/path.go

This PR adds some utility functions, initializer function like NewXxx() and getters of some attributes.

packet/bgp: Add some utility functions

---

server/peer.go
server/server.go

When GoBGP dropped adj-Rib-out per Peer, we fixed to send the same Route Target Membership (RTM) NLRI even if it is already sent. This can cause the infinite UPDATE loop when Route Reflector(RR) reflects RTM NLRI to its clients.
For example, the following situation causes the infinite UPDATE loop.
Topology:
```text
+----- RR -----+
|              |
Client1        Client2
```
When Client1 has VRF with RT 65000:1 and sends a RTM NLRI to RR, then RR reflects the NLRI to Client2. If a new VRF with the same RT 65000:1 on Client2 is created, Client2 will notify it to RR, then RR calculates the best, but RR will send the NLRI from Client2 to Client1 even if it is not the best. Client1 receives the NLRI again, calculates the best and re-sends the best. Then, RR reflects the received NLRI ... …

server: Avoid infinite UPDATE loop of RTM NLRI

---

server/server.go

server/server: Fix typo

---

packet/bgp/bgp.go

fix a mess in the commit 388ef503f2c9cae.

packet/bgp: remove bogus debug print

---

server/server.go
table/path.go

fix add-path with vrf-neighbor

---

test/lib/quagga.py
test/scenario_test/bgp_confederation_test.py
test/scenario_test/bgp_router_test.py

This PR improves the stability of the following scenario tests
- bgp_confederation_test.py
- bgp_router_test.py

scenario_test: Improve stability of some tests

---

server/server.go

server: fix infinite rtc update loop with addpath

---

table/adj.go
table/adj_test.go

table: fix DropStale method in AdjRib

---

api/util.go

the commit 8c453bc9369e4cd96d19b9598bebb0ea2e23e991 fixes
NewROAListFromApiStructList() to check the error strictly. However,
this breaks the rpki table command like the following.
$ gobgp rpki table
invalid CIDR address: 1.0.16.0
NewROAListFromApiStructList() has a bug about getting the address
family from an IP address. The address family was not used (other
information are used though) so before the commit, the command worked.

api: fix rpki regression

---

server/server.go

fix a bug that doesn't return validation results at all.

server: fix GetRib() with rpki

---

server/server.go

server: fix AddPath to return uuid

---

server/server.go
server/server_test.go

server: exclude RTC for softreset if not specified

---

internal/pkg/table/path.go
pkg/server/server.go

https://github.com/osrg/gobgp/issues/1786

use function Equal() instead of build-in compare

---

.travis.yml
docs/sources/lib.md

also enable the CI for it again.

fix library usage example

---

pkg/server/peer.go
pkg/server/server.go

#1804 Draft code to fix the issue...

pkg/server: handleUpdate() should not inject echo route from RR

---

internal/pkg/table/policy.go

table: remove DIRECTION_IN completely

---

cmd/gobgp/cmd/common.go
cmd/gobgp/cmd/neighbor.go
cmd/gobgpd/main.go
pkg/server/grpc_server.go
pkg/server/server.go
pkg/server/server_test.go

Like other ListPolicy*() functions, if no conditions are specified,
all assignments are returned.
close #1427

pkg/server: ListPolicyAssignment() returns all assignments by default

---

tools/pyang_plugins/README.rst

Python 2 is necessary.
fixes #1801
[skip ci]

tools: update pyang_plugins/README.rst

---

pkg/server/fsm.go
pkg/server/server.go

https://github.com/osrg/gobgp/issues/1834

fsm: get rid of dead lock

---

cmd/gobgp/cmd/neighbor.go

https://github.com/osrg/gobgp/issues/1836

cli: fix nil pointer in showNeighbor

---

pkg/server/bmp.go
pkg/server/grpc_server.go
pkg/server/mrt.go
pkg/server/server.go
pkg/server/server_test.go
pkg/server/zclient.go

Watcher uses the internal data structures so should be private. Add new native APIs.

Replace Watcher

---

cmd/gobgpd/main.go
docs/sources/lib.md
pkg/server/grpc_server.go
pkg/server/server.go

make gRPC server private

---

pkg/server/peer.go
pkg/server/server.go

Some deadlocks still remain. It'll occur when using multiple peers. This PR will fix them as workaround.

Avoid deadlock

---

docs/sources/lib.md
pkg/server/grpc_server.go
pkg/server/server.go

https://github.com/osrg/gobgp/issues/1763#issuecomment-437594975
Follow Chris's proposal; consistent with the rest of the APIs.

server: change monitor API design

---

pkg/server/grpc_server.go
pkg/server/server.go
pkg/server/server_test.go

https://github.com/osrg/gobgp/issues/1763#issuecomment-437594975
Follow Chris's proposal; more consistent with gRPC streaming API.
Also supports context properly.

server: change List API design

---

pkg/packet/bgp/validate.go

packet: fix ValidateAttribute() to handle ipv6 addresss

---

BUILD.md
README.md

docs: add BUILD.md, development guide

---

docs/sources/grpc-client.md

docs: fix outdated comment of the gRPC API examples

---

BUILD.md

docs: add project layout description to BUILD

---

pkg/server/server.go
pkg/server/server_test.go

server: kill getNeighbor()

---

BUILD.md

docs: add releases to BUILD

---

pkg/server/server.go

This is to solve https://github.com/osrg/gobgp/issues/1939
It deletes dynamic neighbors only if graceful restart is not configured, otherwise deletes them when the restart timer expires.

Allow graceful restart for dynamic neighbors

---

pkg/server/server.go

https://github.com/osrg/gobgp/commit/318a91e31b8baed86bb66a3767525da68ae49a5d
The above commit added a bug to close a closed channel; after deleting
a dynamic neighbor, handleFSMMessage() must return. Otherwise
cleanInfiniteChannel() is called twice.
https://travis-ci.org/osrg/gobgp/jobs/483896487
close #1945 

server: dynamic neighbor deletion panic

---

README.md
docs/sources/lib-ls.md

This PR adds a simple example showing how to use BGP-LS in the library mode.

Add BGP-LS usage example

---

internal/pkg/zebra/zapi.go

Fix bug reported in issue #1941

Fix bug: processing MPLS label in nexthop update message

---

BUILD.md

the dep command isn't necessary now.

doc: update BUILD.md

---

cmd/gobgp/neighbor.go

make policy printing same with v1.x

cmd/gobgp: fix policy printing

---

docs/sources/cli-command-syntax.md

docs: delete the description of obsolete mrt cli commands

---

docs/sources/lib.md

docs: add v6 route example to lib

---

internal/pkg/table/table_manager.go
pkg/server/server.go
pkg/server/zclient.go

Deleteing goroutine for assignMplsLabel and moveing code relating MPLS  L3VPN (introduced from PR #1992, commit 3a79ad3fdcbb7af0b7911a9c610c6e7af970ad6d) from table_manager.go to zclient.go

Deleteing goroutine for assignMplsLabel

---

pkg/server/bmp.go
pkg/server/fsm.go
pkg/server/server.go

Sends peerdown message when a peer is de-condigured and down.

server: broadcast BMPPeerDownMessage for peer deletion

---

.travis.yml

travis: update go version to 1.12

---

pkg/server/grpc_server.go

Fixed the bug to ignore grpc listen failure.

server: handle grpc listen failure as fatal error

---

pkg/packet/bgp/bgp.go

Ref. https://www.ietf.org/id/draft-ietf-bess-evpn-bum-procedure-updates-05.txt

Initial evpn I-PMSI

---

cmd/gobgp/neighbor.go
pkg/server/server.go

server: fix ListPath handle UseMultiPath option

---

pkg/server/fsm.go

passive mode configuration is just ignored. Fixed it to work.

server: fix passive-mode

---

pkg/server/grpc_server.go

Somehow the state isn't updated.

server: fix path validatoin result regression

---

BUILD.md

docs: update BUILD.md for module support

---

go.mod
go.sum

update module dependency

---

test/scenario_test/route_server_policy_test.py

This patch include following changes.
* Fixing `route_server_policy_test.py` which has not been executed correctly since a commit #0f102be9 was applied
* Removing unnecessary test `InPolicyUpdate2`
* Reusing `InPolicyRejectImplicitWithdraw` as `ImportPolicyRejectImplicitWithdraw`

Fix route server scenario_test

---

docs/sources/policy.md

docs: add how policy and soft reset works

---

.travis.yml

vendor directory doesn't exist anymore.

travis: simplify unit test command

---

internal/pkg/table/destination.go
internal/pkg/table/path.go

table: delete unused reason in Path struct

---

pkg/server/zclient.go

This PR fixes lookup for pathVrfMap (introducing in commit 276518c8269a2403bf79cdeba7c33b644c238214) of zclient.go. 
Current source code fails lookup because the lookup key is a pointer. This PR uses Path.Equal() in for loop as a lookup method.

fix MPLS L3VPN functionality of zapi

---

.goreleaser.yml

update goreleaser config file

---

pkg/packet/bgp/bgp.go

pkg/packet/bgp: fix PathAttributeAs4Path to accept empty AS_PATH

---

pkg/server/server_test.go

test uuid map leak with implict withdraw.

server: add addpath api leak test

---

internal/pkg/table/path.go

table: remove unused validation in originInfo struct

---

README.md

README: add link to confederation doc

---

pkg/server/grpc_server.go
pkg/server/server.go

server: fix mrt injection race

---

docs/sources/rpki.md

docs: update rpki config

---

pkg/server/grpc_server.go

server: advoid ListPath's long lock

---

internal/pkg/table/policy_test.go

table: add NewSingleAsPathMatch unittest

---

cmd/gobgp/rpki.go

gobgp: fix rpki table printing

---

internal/pkg/config/util.go

need to reset session when gr config is changed

---

test/lib/bagpipe.py
test/lib/base.py
test/scenario_test/README.md

test: rm pipework functions

---

internal/pkg/table/roa.go
internal/pkg/table/roa_test.go
pkg/server/rpki.go
pkg/server/server.go

As the name implies, table/ is more appropriate for roa table code.

move roa table code to table/ from server/

---

internal/pkg/table/roa.go
pkg/server/grpc_server.go

table: use net.IPNet for roa instead of homegrown IPPrefix structure

---

go.mod
go.sum
internal/pkg/table/roa.go
internal/pkg/table/roa_test.go

table: replace radix with crit-bit algo for roa

---

internal/pkg/table/policy.go

table: replace radix with crit-bit algo for policy

---

internal/pkg/table/message.go

table: handle staticcheck's warnings

---

internal/pkg/config/util.go

Signed-off-by: Faicker Mo <faicker.mo@ucloud.cn>

config: peer groups support ebgp multihop

---

docs/sources/zebra.md
internal/pkg/config/default.go
internal/pkg/zebra/zapi.go
tools/pyang_plugins/gobgp.yang

This PR enhances zapi functionality for supporting FRRouting 7.2

Supporting FRR7.2

---

internal/pkg/zebra/zapi.go

This PR fixes bug of PR #2229 .

bug fix in zebra integration for frr7.2

---

.github/workflows/release.yml

github: fix release action to generate proper changelog

---

docs/sources/cli-operations.md

docs: update cli output

---

pkg/packet/bgp/bgp.go

optimized EVPNMacIPAdvertisementRoute, SerializeExtendedCommunities and PathAttributeIP6ExtendedCommunities allocations.

optimized packet/bgp allocations

---

pkg/packet/bgp/bgp.go

* used stack-based buf for serializing numbers
* added capacity to buffer allocations
* replaced `fmt.Errorf("string without any %fmt directive")` with `errors.New()`
* replaced `fmt.Sprint(a, b)` with `a + b`

optimized allocations in packet/bgp

---

pkg/packet/mrt/mrt.go

packet: silence staticcheck warning

---

pkg/packet/mrt/mrt.go

packet: fix typos

---

.travis.yml

travis-ci: update ubuntu docker package url

---

.goreleaser.yml

goreleaser: disable cgo completely

---

pkg/server/fsm.go

server: don't send empty ExtendedNexthop capability

---

docs/sources/flowspec.md

Should be ether-type instead of fragment

fix fragment with ether-type

---

pkg/packet/bgp/bgp.go

implement LsAddrPrefix marshalJson() function
Fix #2293

implement LsAddrPrefix marshal json function

---

README.md

README: update slack link

---

pkg/packet/bgp/bgp.go
pkg/packet/bgp/bgp_test.go

packet: handle malformed prefix len

---

.github/workflows/ci.yml

the same ci that we run on travis-ci. github actions is much faster.

run ci on github actions

---

internal/pkg/apiutil/attribute.go
pkg/server/grpc_server.go
pkg/server/server_test.go

server: handle bogus addpath argument

---

internal/pkg/config/util.go
pkg/server/grpc_server.go

server: fix conversion from api.RouteAction to config.DefaultPolicyType

---

pkg/server/util.go

server: fix AdministrativeCommunication message parser

---

pkg/server/grpc_server.go
pkg/server/grpc_server_test.go

Add support for the gRPC server to listen on a unix domain socket

---

cmd/gobgp/rpki.go

cmd/rpki: support delete api

---

pkg/server/fsm.go

when gobgp and its peer encounter hold-time expiry at the same time, gobgp will be in a dead lock state，which leads to a false bgp established state but the tcp connection is closed. The details are as follows:
1. gobgp encounters hold-time expiry, so it creates BGP_ERROR_HOLD_TIMER_EXPIRED notification message and pushes the message to outgoing channel. And if GracefulRestart is not enabled, so it just returns, but blocked on 'defer wg.Wait()', waiting for sendMessageloop and recvMessageloop goroutines to exit. (source code is in function established of file pkg/server/fsm.go)
2. gobgp receives the BGP_ERROR_HOLD_TIMER_EXPIRED notification message which is sent by its bgp peer. so it pushes a fsmNotificationRecv message to stateReasonCh channel and return nil. And the code go into …

Fixed dead lock bug caused by hold-time expiry

---

pkg/server/server.go

server: fix ListVrf api to handle Name member

---

cmd/gobgp/neighbor.go

fix #2479: add route-server-client and route-reflector-client neighbor

---

.github/workflows/ci.yml
BUILD.md
tools/completion/README.md
tools/pyang_plugins/bgpyang2golang.py

update v3 suffix

---

.github/workflows/ci.yml
pkg/server/sockopt_openbsd.go

add build tests on freebsd, openbsd, and darwin.

ci: add crossbuild tests

---

BUILD.md

doc: update build guide

---

.github/workflows/ci.yml
docs/sources/lib-ls.md

ci: add lib-ls example

---

pkg/server/bmp.go

server: fix bmp regression due to WatchEvent API

---

internal/pkg/config/default.go
pkg/server/server.go

server: fix bmp configuration via grpc

---

pkg/server/server.go

I observed that the `EndOfRibReceived` state is "stuck" set to true except when a peer is restarting due to GR. We should always ensure that `EndOfRibReceived` is cleared even when this is not the case otherwise we cannot tell when a peer has sent all of its initial route updates when re-establishing.

Ensure EndOfRibReceived is always cleared on Peer Down

---

cmd/gobgp/bmp.go

cmd/gobgp: fix missing pre policy

---

cmd/gobgp/bmp.go

make output of gobgp mrt pretty

---

cmd/gobgp/bmp.go

fix gobmp mrt command downtime

---

cmd/gobgp/neighbor.go
go.mod

cmd: avoid deprecated string.Title API

---

pkg/server/server.go

server: handle uuid error in AddPath API

---

.github/workflows/ci.yml
README.md

- docs: update badges on README
- Build Status shows Travis CI status, but Travis CI is not used.
- Add Go Report, Tests, Go Reference, Releases and LICENSE badges.
- ci: add push event for ci trigger
- Enable to show CI workflow badge and run CI on forked branch.

docs: update badges on README

---

.github/workflows/ci.yml
.github/workflows/release.yml

- actions/checkout@v3
- actions/setup-go@v3
- golangci/golangci-lint-action@v3
- actions/upload-artifact@v3
- actions/download-artifact@v3
- goreleaser/goreleaser-action@v3

ci: update actions

---

pkg/server/sockopt_linux_test.go

Fix TCPM5Sig tests on big-endian host

---

internal/pkg/zebra/zapi.go

This patch addresses the issue #2681

Accommodate FRRouting interfaceNameSize changes

---

pkg/packet/bgp/bgp.go

packet: fix FQDN capability parser

---

pkg/packet/bgp/bgp.go

packet: fix software version capability parser

---

go.mod
go.sum

fix: #2835 
update go latest stable to go 1.22.6 fix CVE

fix: go CVE

---

tools/pyang_plugins/README.md

Improve the instructions so that work can be done in directories other than $HOME.

doc: Improve instructions to generate bgp_configs.go

---

pkg/server/server.go

When we apply nexthop-unchanged action to the locally-originated route with unspecified nexthop (0.0.0.0 or ::), we advertise the path with unspecified nexthop. This may ends up with the session shutdown with Invalid Update Message Notification (only tested with FRR 10.2.1, following is a capture of the path with`bgp allow-martian-nexthop` which forcefully allows such an invalid nexthop).
```
BGP routing table entry for 10.244.0.0/24, version 5
Paths: (2 available, best #2, table default)
Advertised to non peer-group peers:
fc00:c111::2 fc00:c111::5
65000
0.0.0.0 (inaccessible, import-check enabled) from fc00:c111::5 (172.19.0.5)
Origin IGP, invalid, external
Last update: Tue Mar 18 16:41:54 2025
```
Fix this issue by setting table.PolicyOptions.OldNextHop to the local peering address …

Fix invalid nexthop advertisement with nexthop-unchanged

---

api/gobgp.pb.go
api/gobgp_grpc.pb.go
cmd/gobgp/root.go
pkg/server/grpc_server.go
proto/api/gobgp.proto

api: remove google.protobuf.Empty usage

---

api/gobgp.pb.go
proto/api/gobgp.proto

api: Make field names lower_snake_case

---

api/gobgp.pb.go
cmd/gobgp/policy.go
internal/pkg/table/policy.go
pkg/server/grpc_server.go
proto/api/gobgp.proto

api: Fix MedAction Enum

---

api/gobgp.pb.go
internal/pkg/table/policy.go
pkg/server/grpc_server.go
proto/api/gobgp.proto

api: Fix OriginType Enum

---

api/gobgp.pb.go
cmd/gobgp/global.go
cmd/gobgp/mrt.go
cmd/gobgp/neighbor.go
docs/sources/lib-srpolicy.md
pkg/metrics/metrics_test.go
pkg/server/grpc_server.go
pkg/server/server.go
pkg/server/server_test.go
proto/api/gobgp.proto

api: Fix TableType Enum

---

api/gobgp.pb.go
cmd/gobgp/policy.go
internal/pkg/table/policy.go
pkg/server/grpc_server.go
proto/api/gobgp.proto

Use it for AsPathLength and CommunityCount messages.

api: Add Comparison enum

---

api/gobgp.pb.go
cmd/gobgp/neighbor.go
pkg/config/oc/util.go
pkg/server/server.go
proto/api/gobgp.proto

api: Fix AdminState Enum in PeerState

---

api/gobgp.pb.go
cmd/gobgp/neighbor.go
pkg/config/oc/util.go
pkg/server/grpc_server.go
proto/api/gobgp.proto

api: Fix RemovePrivate Enum

---

api/gobgp.pb.go
cmd/gobgp/policy.go
internal/pkg/table/policy.go
pkg/server/grpc_server.go
pkg/server/server_test.go
proto/api/gobgp.proto

api: Fix Type Enum in MatchSet

---

api/gobgp.pb.go
pkg/config/oc/util.go
pkg/server/grpc_server.go
proto/api/gobgp.proto

api: Fix PeerType Enum

---

api/gobgp.pb.go
cmd/gobgp/neighbor.go
cmd/gobgp/policy.go
internal/pkg/table/policy.go
pkg/server/grpc_server.go
proto/api/gobgp.proto

Used for Validation and Conditions messages.

api: Add ValidationState enum

---

pkg/server/grpc_server.go

Fix commit 39595946935a ("api: Fix SessionState enum prefix").

server: fix peerstate conversion

---

pkg/server/server_test.go

by starting the watcher after adding the peer, we don't have the guaranty to receive the state event.
so it is needed to start the watcher before and wait for it after adding the peer.

fix(test): fix new waitState

---

pkg/server/fsm_test.go

*testing.T can be access by other means than the MockConnection
the locking mechanism does not protect it from race condition
https://github.com/osrg/gobgp/actions/runs/16195741427/job/45721651605#step:4:1314

fix: remove *testing.T from MockConnection

---

pkg/server/fsm_test.go

update fsm test by using standard net.Pipe to correctly implement all net.Conn features (SetReadDeadline, etc...)

fix: update fsm test

---

pkg/packet/bgp/bgp.go

Use netip.Addr for EncapNLRI instead of IPAddrPrefixDefault because EncapNLRI doesn't include IP prefix. It include an endpoint; IPv4 or IPv6 address.
Avoid repurposing IPAddrPrefixDefault outside its intended use for the future improvement.

packet/bgp: use netip.Addr for EncapNLRI instead of IPAddrPrefixDefault

---

pkg/packet/bgp/bgp.go
pkg/packet/bgp/validate.go
pkg/server/fsm.go
pkg/server/fsm_test.go

Replace net.IP with netip.Addr for BGPOpen.

pkg/packet/bgp: use netip for BGPOpen

---

pkg/packet/bgp/bgp.go

Replace net.IP with netip.Addr for PathAttributeAggregator.

pkg/packet/bgp: use netip for PathAttributeAggregator

---

pkg/packet/bgp/bgp.go

Replace net.IP with netip.Addr for TunnelEncapSubTLVEgressEndpoint.

pkg/packet/bgp: Use netip for TunnelEncapSubTLVEgressEndpoint

---

pkg/packet/bgp/bgp.go

Replace net.IP with netip.Addr for IngressReplTunnelID.

pkg/packet/bgp: Use netip for IngressReplTunnelID

---

pkg/packet/mrt/mrt.go
pkg/packet/mrt/mrt_test.go
pkg/server/mrt.go

Replace net.IP with netip.Addr for mrt code.

pkg/packet/mrt: use netip

---

pkg/packet/bmp/bmp.go
pkg/packet/bmp/bmp_test.go
pkg/server/bmp.go

Replace net.IP with netip.Addr for bmp code.

pkg/packet/bmp: use netip

---

cmd/gobgp/global.go
pkg/apiutil/attribute.go
pkg/packet/bgp/bgp.go

Replace net.IP with netip.Addr for LsTLVSrv6SIDInfo.

pkg/packet/bgp: use netip for LsTLVSrv6SIDInfo

---

pkg/packet/bgp/bgp.go

No need to implement them for NLRI.

packet/bgp: remove AFI and SAFI in FlowSpecNLRI

---

pkg/server/server.go

use netip.Addr for watchEventPeer insteaf of net.IP

server: use netip for watchEventPeer

---

internal/pkg/table/table_manager.go
pkg/server/zclient.go
pkg/server/zclient_test.go
pkg/zebra/zapi.go
pkg/zebra/zapi_test.go

zebra: use netip

---

pkg/server/server.go
pkg/server/server_test.go

I found bug with eBGP withdraw handling (scenario you can see in test or in comment)

fix: fix route stuck on eBGP filterpath

---

pkg/server/fsm.go

server: remove fsm in FsmMsg

---

pkg/server/fsm.go

sentNotification in fsmHandler isn't set; it's always nil and useless.

server/fsm: remove sentNotification in fsmHandler

---

pkg/server/fsm.go

replace fsm intermediate infinite channel with simpler normal channel. We don't need to use infinite channel for incoming anymore.

fix: replace fsm intermediate infinite channel with normal channel

---

pkg/server/fsm.go
pkg/server/peer.go
pkg/server/server.go

Avoid the following boilerplate:
slog.String("Topic", "Peer"), slog.String("Key", peer.ID()),

server: create peer specific logger

---

pkg/server/fsm.go
pkg/server/peer.go

Make fsm's rtcEORWait lock-free for simplicity.

server: use atomic.Bool for rtcEORWait

---

pkg/server/fsm.go
pkg/server/peer.go
pkg/server/server.go

make sure that only fsm.go accesses to fsm.h.

server: make fsm handler private

---

pkg/server/fsm.go

server: lock fsm.lock to access to Timers.Config

---

pkg/server/fsm.go

Avoid fsm lock every received message.

server: add isEBGP and isConfed to fsm

---

pkg/server/fsm.go

Open message should be sent before the state becomes opensent state.

server/fsm: send open before moving to opensent state
